# Generated by Django 5.2.7 on 2025-12-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Receber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "forma_de_recebimento",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Forma de recebimento"
                    ),
                ),
                (
                    "data_vencimento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data vencimento"
                    ),
                ),
                (
                    "cliente",
                    models.CharField(max_length=255, null=True, verbose_name="Cliente"),
                ),
                (
                    "categoria",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Categoria"
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Valor a ser recebido",
                    ),
                ),
                (
                    "valor_estoque",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Valor em estoque",
                    ),
                ),
                (
                    "observacoes",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Observações"
                    ),
                ),
                (
                    "data_pagamento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data pagamento"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="Agendado", max_length=30, verbose_name="Status"
                    ),
                ),
            ],
        ),
    ]
