# Generated by Django 5.2.6 on 2025-12-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exibir_contas_pagar",
                    models.BooleanField(default=True, verbose_name="Contas a Pagar"),
                ),
                (
                    "exibir_gastos_operacionais",
                    models.BooleanField(
                        default=True, verbose_name="Gastos Operacionais (Caixa)"
                    ),
                ),
                (
                    "exibir_folha",
                    models.BooleanField(
                        default=False, verbose_name="Folha de Pagamento"
                    ),
                ),
                (
                    "exibir_comissoes",
                    models.BooleanField(default=False, verbose_name="Comissões"),
                ),
                (
                    "exibir_receber",
                    models.BooleanField(default=True, verbose_name="Contas a Receber"),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Receber",
        ),
    ]
