# Generated by Django 5.2.7 on 2025-12-14 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_dashboardconfig_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Receber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "forma_de_recebimento",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Forma de recebimento"
                    ),
                ),
                (
                    "data_vencimento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data vencimento"
                    ),
                ),
                (
                    "cliente",
                    models.CharField(max_length=255, null=True, verbose_name="Cliente"),
                ),
                (
                    "categoria",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Categoria"
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Valor a ser recebido",
                    ),
                ),
                (
                    "valor_estoque",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Valor em estoque",
                    ),
                ),
                (
                    "observacoes",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Observações"
                    ),
                ),
                (
                    "data_pagamento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data pagamento"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="Agendado", max_length=30, verbose_name="Status"
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="dashboardconfig",
            options={
                "verbose_name": "Configuração do Dashboard",
                "verbose_name_plural": "Configuração do Dashboard",
            },
        ),
        migrations.RemoveField(
            model_name="dashboardconfig",
            name="exibir_receber",
        ),
        migrations.RemoveField(
            model_name="dashboardconfig",
            name="user",
        ),
        migrations.AddField(
            model_name="dashboardconfig",
            name="exibir_recebimentos",
            field=models.BooleanField(
                default=True, verbose_name="Exibir Contas a Receber"
            ),
        ),
        migrations.AlterField(
            model_name="dashboardconfig",
            name="exibir_comissoes",
            field=models.BooleanField(default=False, verbose_name="Exibir Comissões"),
        ),
        migrations.AlterField(
            model_name="dashboardconfig",
            name="exibir_contas_pagar",
            field=models.BooleanField(
                default=True,
                help_text="Boletos, Utilidades, Fornecedores (Obrigações Futuras)",
                verbose_name="Exibir Contas a Pagar",
            ),
        ),
        migrations.AlterField(
            model_name="dashboardconfig",
            name="exibir_folha",
            field=models.BooleanField(
                default=False, verbose_name="Exibir Folha de Pagamento"
            ),
        ),
        migrations.AlterField(
            model_name="dashboardconfig",
            name="exibir_gastos_operacionais",
            field=models.BooleanField(
                default=True,
                help_text="Gasolina, Gastos Gerais (Pagos no ato)",
                verbose_name="Exibir Gastos Operacionais",
            ),
        ),
    ]
