# Generated by Django 5.2.7 on 2025-12-20 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_receber_alter_dashboardconfig_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DashboardConfig",
        ),
    ]
