# Generated by Django 5.2.7 on 2025-12-24 01:47

import fernet_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_perfilusuario_delete_receber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfilusuario",
            name="cpf",
            field=fernet_fields.fields.EncryptedCharField(
                help_text="Formato: 000.000.000-00", max_length=14, verbose_name="CPF"
            ),
        ),
    ]
