# Generated by Django 5.2.7 on 2025-12-05 19:01

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("funcionarios", "0004_remove_dadostrabalhistas_saldo_banco_horas"),
    ]

    operations = [
        migrations.CreateModel(
            name="BancoHoras",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "saldo",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Saldo atual de horas no banco de horas",
                        max_digits=10,
                    ),
                ),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "funcionario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="banco_horas",
                        to="funcionarios.funcionario",
                    ),
                ),
            ],
        ),
    ]
