# Generated by Django 5.2.7 on 2025-12-05 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banco_horas", "0001_initial"),
        ("funcionarios", "0004_remove_dadostrabalhistas_saldo_banco_horas"),
    ]

    operations = [
        migrations.CreateModel(
            name="LancamentoHoras",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("horas", models.DecimalField(decimal_places=2, max_digits=6)),
                ("motivo", models.CharField(blank=True, max_length=255)),
                ("data", models.DateTimeField(auto_now_add=True)),
                (
                    "funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lancamentos_horas",
                        to="funcionarios.funcionario",
                    ),
                ),
            ],
        ),
    ]
