# Generated by Django 5.2.6 on 2025-12-08 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("banco_horas", "0002_lancamentohoras"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lancamentohoras",
            name="motivo",
        ),
    ]
