# Generated by Django 5.2.7 on 2026-01-06 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banco_horas", "0003_remove_lancamentohoras_motivo"),
    ]

    operations = [
        migrations.AddField(
            model_name="bancohoras",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data da Exclusão"
            ),
        ),
        migrations.AddField(
            model_name="bancohoras",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Está na Lixeira?"),
        ),
    ]
