# Generated by Django 5.2.7 on 2026-01-11 15:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banco_horas", "0005_lancamentohoras_deleted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lancamentohoras",
            name="valor_hora",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Valor da hora neste lançamento específico",
                max_digits=10,
                verbose_name="Valor da Hora (R$)",
            ),
        ),
    ]
