# Generated by Django 5.2.6 on 2026-01-28 17:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banco_horas", "0006_lancamentohoras_valor_hora"),
    ]

    operations = [
        migrations.AddField(
            model_name="lancamentohoras",
            name="descricao",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Descrição"
            ),
        ),
        migrations.AlterField(
            model_name="lancamentohoras",
            name="data",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Data do Evento"
            ),
        ),
    ]
