# Generated by Django 5.2.7 on 2026-01-06 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoGlobal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lixeira_ativa",
                    models.BooleanField(
                        default=True,
                        help_text="Se desativado, exclusões serão permanentes imediatamente.",
                        verbose_name="Ativar Lixeira",
                    ),
                ),
                (
                    "dias_retencao_lixeira",
                    models.IntegerField(
                        default=180,
                        help_text="Após este período, itens na lixeira serão excluídos permanentemente (ex: 180 dias = 6 meses).",
                        verbose_name="Dias de retenção na Lixeira",
                    ),
                ),
                (
                    "limpeza_automatica_ativa",
                    models.BooleanField(
                        default=False, verbose_name="Ativar Limpeza de Dados Antigos"
                    ),
                ),
                (
                    "anos_retencao_historico",
                    models.IntegerField(
                        default=2,
                        help_text="Registros financeiros/RH mais antigos que isso serão arquivados/excluídos.",
                        verbose_name="Anos de retenção de histórico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração Global",
                "verbose_name_plural": "Configurações Globais",
            },
        ),
    ]
