# Generated by Django 5.2.7 on 2026-01-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracoes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="configuracaoglobal",
            name="anos_retencao_historico",
        ),
        migrations.AddField(
            model_name="configuracaoglobal",
            name="meses_retencao_historico",
            field=models.IntegerField(
                default=18, verbose_name="Meses de Retenção do Histórico (Padrão: 18)"
            ),
        ),
        migrations.AlterField(
            model_name="configuracaoglobal",
            name="limpeza_automatica_ativa",
            field=models.BooleanField(
                default=True, verbose_name="Ativar Limpeza de Histórico?"
            ),
        ),
    ]
