# Generated by Django 5.2.6 on 2026-01-17 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "configuracoes",
            "0002_remove_configuracaoglobal_anos_retencao_historico_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracaoglobal",
            name="modo_escuro_ativo",
            field=models.BooleanField(
                default=False, verbose_name="Ativar Modo Escuro Global"
            ),
        ),
    ]
