# Generated by Django 5.2.6 on 2026-01-17 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configuracoes", "0003_configuracaoglobal_modo_escuro_ativo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="configuracaoglobal",
            name="modo_escuro_ativo",
        ),
    ]
