# Generated by Django 5.2.6 on 2025-12-28 19:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Socio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="CategoriaSocio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grupo",
                    models.CharField(
                        choices=[
                            ("RENDA_FAMILIAR", "Renda Familiar"),
                            ("HABITACAO", "Habitação"),
                            ("AUTOMOVEL", "Automóvel"),
                            ("DESPESAS_PESSOAIS", "Despesas Pessoais"),
                            ("SAUDE", "Saúde"),
                            ("EDUCACAO", "Educação"),
                            ("LAZER", "Lazer"),
                            ("DEPENDENTES", "Dependentes"),
                            ("INVESTIMENTOS", "Investimentos/Dívidas"),
                            ("OUTROS", "Outros"),
                        ],
                        max_length=50,
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["grupo", "nome"],
                "unique_together": {("grupo", "nome")},
            },
        ),
        migrations.CreateModel(
            name="LancamentoSocio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Data"
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor (R$)"
                    ),
                ),
                (
                    "observacao",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Observação"
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="socios.categoriasocio",
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "socio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="socios.socio",
                        verbose_name="Sócio",
                    ),
                ),
            ],
            options={
                "ordering": ["-data"],
            },
        ),
    ]
