# Generated by Django 5.2.7 on 2026-01-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socios", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categoriasocio",
            options={"ordering": ["id"]},
        ),
        migrations.AlterField(
            model_name="categoriasocio",
            name="grupo",
            field=models.CharField(
                choices=[
                    ("RENDA_FAMILIAR", "Renda Familiar"),
                    ("HABITACAO", "Habitação"),
                    ("SAUDE", "Saúde"),
                    ("TRANSPORTE", "Transporte"),
                    ("AUTOMOVEL", "Automóvel"),
                    ("DESPESAS_PESSOAIS", "Despesas Pessoais"),
                    ("LAZER", "Lazer"),
                    ("DEPENDENTES", "Dependentes"),
                ],
                max_length=50,
            ),
        ),
    ]
