# Generated by Django 5.2.6 on 2026-01-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socios", "0003_socio_deleted_at_socio_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="lancamentosocio",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data da Exclusão"
            ),
        ),
        migrations.AddField(
            model_name="lancamentosocio",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Está na Lixeira?"),
        ),
    ]
