# Generated by Django 5.2.7 on 2026-01-11 16:46

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0002_alter_cliente_cpf"),
        ("funcionarios", "0007_funcionario_deleted_at_funcionario_is_deleted"),
    ]

    operations = [
        migrations.CreateModel(
            name="Empreitada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Está na Lixeira?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data da Exclusão"
                    ),
                ),
                (
                    "ambiente",
                    models.CharField(
                        help_text="Ex: Cozinha, Quarto Casal, etc.", max_length=200
                    ),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, verbose_name="Descrição Detalhada"),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Valor Total da Empreitada",
                    ),
                ),
                ("data_inicio", models.DateField()),
                ("data_fim_estimada", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EM_ANDAMENTO", "Em Andamento"),
                            ("CONCLUIDA", "Concluída"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="EM_ANDAMENTO",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empreitadas",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empreitadas",
                        to="funcionarios.funcionario",
                    ),
                ),
            ],
            options={
                "ordering": ["-data_inicio"],
            },
        ),
        migrations.CreateModel(
            name="PagamentoEmpreitada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Está na Lixeira?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data da Exclusão"
                    ),
                ),
                (
                    "data",
                    models.DateField(default=django.db.models.functions.datetime.Now),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor retirado pelo funcionário",
                        max_digits=10,
                    ),
                ),
                (
                    "observacao",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Observação (Ex: Adiantamento p/ almoço)",
                    ),
                ),
                (
                    "empreitada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagamentos",
                        to="empreitadas.empreitada",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
