# Generated by Django 5.2.7 on 2025-10-12 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Funcionario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("data_nascimento", models.DateField(blank=True, null=True)),
                ("natural_de", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Feminino"), ("O", "Outro")],
                        default="O",
                        max_length=1,
                    ),
                ),
                (
                    "grau_instrucao",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Analfabeto"),
                            (2, "1ª a 4ª Série incompleta"),
                            (3, "4ª Série completa"),
                            (4, "5ª a 8ª Série incompleta"),
                            (5, "1º Grau completo"),
                            (6, "2º Grau incompleto"),
                            (7, "2º Grau completo"),
                            (8, "Superior incompleto"),
                            (9, "Superior completo"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "estado_civil",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SOL", "Solteiro(a)"),
                            ("CAS", "Casado(a)"),
                            ("DIV", "Divorciado(a)"),
                            ("VIU", "Viúvo(a)"),
                            ("UNI", "União Estável"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("conjuge", models.CharField(blank=True, max_length=200, null=True)),
                ("nome_pai", models.CharField(blank=True, max_length=200, null=True)),
                ("nome_mae", models.CharField(blank=True, max_length=200, null=True)),
                ("numero_filhos", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="EnderecoFuncionario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endereco", models.CharField(max_length=255)),
                ("numero", models.CharField(max_length=10)),
                ("bairro", models.CharField(max_length=100)),
                ("cidade", models.CharField(max_length=100)),
                ("uf", models.CharField(max_length=2)),
                ("cep", models.CharField(max_length=10)),
                (
                    "funcionario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="endereco",
                        to="funcionarios.funcionario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentosFuncionario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pis_pasep", models.CharField(blank=True, max_length=20, null=True)),
                ("rg", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "rg_orgao_expedidor",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("cpf", models.CharField(max_length=14, unique=True)),
                ("ctps_numero", models.CharField(blank=True, max_length=20, null=True)),
                ("ctps_serie", models.CharField(blank=True, max_length=10, null=True)),
                ("ctps_uf", models.CharField(blank=True, max_length=2, null=True)),
                (
                    "titulo_eleitor",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "certificado_reservista",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "funcionario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="funcionarios.funcionario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DadosTrabalhistas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_admissao_contabilidade", models.DateField()),
                ("data_admissao_marcenaria", models.DateField()),
                ("funcao", models.CharField(max_length=100)),
                ("cbo", models.CharField(blank=True, max_length=20, null=True)),
                ("salario", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "insalubridade",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percentual (%)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "horario_trabalho",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "contrato_experiencia_dias",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "prorrogação_dias",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "funcionario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dados_trabalhistas",
                        to="funcionarios.funcionario",
                    ),
                ),
            ],
        ),
    ]
