# Generated by Django 5.2.6 on 2025-12-02 00:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funcionarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dadostrabalhistas",
            name="horas_extras_acumuladas",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Total de horas extras acumuladas",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="dadostrabalhistas",
            name="horas_utilizadas",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Total de horas já compensadas",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="dadostrabalhistas",
            name="saldo_banco_horas",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                editable=False,
                help_text="Saldo atual de horas no banco de horas",
                max_digits=10,
            ),
        ),
    ]
