# Generated by Django 5.2.6 on 2025-12-02 20:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funcionarios", "0002_dadostrabalhistas_horas_extras_acumuladas_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dadostrabalhistas",
            name="horas_extras_acumuladas",
        ),
        migrations.RemoveField(
            model_name="dadostrabalhistas",
            name="horas_utilizadas",
        ),
        migrations.AlterField(
            model_name="dadostrabalhistas",
            name="saldo_banco_horas",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Saldo atual de horas no banco de horas",
                max_digits=10,
            ),
        ),
    ]
