# Generated by Django 5.2.7 on 2025-12-05 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "funcionarios",
            "0003_remove_dadostrabalhistas_horas_extras_acumuladas_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dadostrabalhistas",
            name="saldo_banco_horas",
        ),
    ]
