# Generated by Django 5.2.7 on 2025-12-24 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funcionarios", "0004_remove_dadostrabalhistas_saldo_banco_horas"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentosfuncionario",
            name="tipo_pis_pasep",
            field=models.CharField(
                blank=True,
                choices=[("PIS", "PIS"), ("PASEP", "PASEP")],
                default="PIS",
                max_length=5,
                null=True,
                verbose_name="Tipo (PIS/PASEP)",
            ),
        ),
    ]
