# Generated by Django 5.2.7 on 2025-12-24 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funcionarios", "0005_documentosfuncionario_tipo_pis_pasep"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentosfuncionario",
            name="pis_pasep",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="PIS/PASEP"
            ),
        ),
    ]
