# Generated by Django 5.2.6 on 2026-01-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funcionarios", "0007_funcionario_deleted_at_funcionario_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="dadostrabalhistas",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data da Exclusão"
            ),
        ),
        migrations.AddField(
            model_name="dadostrabalhistas",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Está na Lixeira?"),
        ),
        migrations.AddField(
            model_name="documentosfuncionario",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data da Exclusão"
            ),
        ),
        migrations.AddField(
            model_name="documentosfuncionario",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Está na Lixeira?"),
        ),
        migrations.AddField(
            model_name="enderecofuncionario",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data da Exclusão"
            ),
        ),
        migrations.AddField(
            model_name="enderecofuncionario",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Está na Lixeira?"),
        ),
    ]
