# Generated by Django 5.2.6 on 2026-03-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funcionarios", "0008_dadostrabalhistas_deleted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcionario",
            name="chave_pix",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Chave PIX"
            ),
        ),
    ]
