# Generated by Django 5.2.6 on 2026-03-08 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funcionarios", "0009_funcionario_chave_pix"),
    ]

    operations = [
        migrations.CreateModel(
            name="BeneficioFuncionario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Está na Lixeira?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data da Exclusão"
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=100,
                        verbose_name="Nome do Benefício (Ex: Odontológico)",
                    ),
                ),
                (
                    "valor_desconto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Valor a Descontar (R$)",
                    ),
                ),
                (
                    "funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beneficios",
                        to="funcionarios.funcionario",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
