# Generated by Django 5.2.6 on 2026-03-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funcionarios", "0010_beneficiofuncionario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funcionario",
            name="numero_filhos",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
