# Generated by Django 5.2.6 on 2026-03-14 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funcionarios", "0011_alter_funcionario_numero_filhos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enderecofuncionario",
            name="bairro",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="enderecofuncionario",
            name="cep",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="enderecofuncionario",
            name="cidade",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="enderecofuncionario",
            name="endereco",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="enderecofuncionario",
            name="funcionario",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="endereco",
                to="funcionarios.funcionario",
            ),
        ),
        migrations.AlterField(
            model_name="enderecofuncionario",
            name="numero",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="enderecofuncionario",
            name="uf",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
