# Generated by Django 5.2.6 on 2025-10-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagar", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagar",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDENTE", "Pendente"),
                    ("PAGO", "Pago"),
                    ("ATRASADO", "Atrasado"),
                ],
                default="PENDENTE",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
