# Generated by Django 5.2.7 on 2025-10-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagar", "0002_alter_pagar_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagar",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pendente", "Pendente"),
                    ("Pago", "Pago"),
                    ("Atrasado", "Atrasado"),
                ],
                default="Pendente",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
