# Generated by Django 5.2.6 on 2025-12-05 20:34

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagar", "0003_alter_pagar_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Boleto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=255, verbose_name="Descrição do Gasto"),
                ),
                (
                    "valor_original",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor Original"
                    ),
                ),
                (
                    "data_vencimento",
                    models.DateField(verbose_name="Data de Vencimento"),
                ),
                (
                    "data_pagamento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Pagamento"
                    ),
                ),
                (
                    "valor_pago",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Valor Pago",
                    ),
                ),
                (
                    "juros",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Juros/Multa",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pendente", "Pendente"),
                            ("Pago", "Pago"),
                            ("Atrasado", "Atrasado"),
                        ],
                        default="Pendente",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "nota_fiscal",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nota Fiscal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Boleto",
                "verbose_name_plural": "Boletos",
            },
        ),
        migrations.CreateModel(
            name="Cheque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=255, verbose_name="Despesa")),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor"
                    ),
                ),
                ("data_emissao", models.DateField(verbose_name="Data de Emissão")),
                (
                    "numero_cheque",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Nº do Cheque"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EMI", "Emitido"),
                            ("COM", "Compensado"),
                            ("DEV", "Devolvido"),
                            ("CAN", "Cancelado"),
                        ],
                        default="EMI",
                        max_length=3,
                        verbose_name="Status",
                    ),
                ),
                (
                    "tipo_entidade",
                    models.CharField(
                        choices=[("F", "Física"), ("J", "Jurídica")],
                        max_length=1,
                        verbose_name="Tipo de Entidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cheque",
                "verbose_name_plural": "Cheques",
            },
        ),
        migrations.CreateModel(
            name="ComissaoArquiteto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_pagamento", models.DateField(verbose_name="Data do Pagamento")),
                (
                    "valor_comissao",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Valor da Comissão",
                    ),
                ),
                ("observacoes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Comissão de Arquiteto",
                "verbose_name_plural": "Comissões de Arquitetos",
            },
        ),
        migrations.CreateModel(
            name="Emprestimo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        max_length=255, verbose_name="Descrição do Empréstimo"
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Valor Total do Empréstimo",
                    ),
                ),
                ("data_inicio", models.DateField(verbose_name="Data de Início")),
                (
                    "data_final_prevista",
                    models.DateField(verbose_name="Data Final Prevista"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FaturaCartao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=255, verbose_name="Descrição do Gasto"),
                ),
                (
                    "valor_original",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor Original"
                    ),
                ),
                (
                    "data_vencimento",
                    models.DateField(verbose_name="Data de Vencimento"),
                ),
                (
                    "data_pagamento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Pagamento"
                    ),
                ),
                (
                    "valor_pago",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Valor Pago",
                    ),
                ),
                (
                    "juros",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Juros/Multa",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pendente", "Pendente"),
                            ("Pago", "Pago"),
                            ("Atrasado", "Atrasado"),
                        ],
                        default="Pendente",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "cartao",
                    models.CharField(
                        choices=[
                            ("PF_SICOOB", "Sicoob PF"),
                            ("PF_BRADESCO", "Bradesco PF"),
                            ("BNDES", "Cartão BNDES"),
                        ],
                        max_length=50,
                        verbose_name="Cartão/Conta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fatura de Cartão",
                "verbose_name_plural": "Faturas de Cartão",
            },
        ),
        migrations.CreateModel(
            name="GastoContabilidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=255, verbose_name="Descrição do Gasto"),
                ),
                (
                    "valor_original",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor Original"
                    ),
                ),
                (
                    "data_vencimento",
                    models.DateField(verbose_name="Data de Vencimento"),
                ),
                (
                    "data_pagamento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Pagamento"
                    ),
                ),
                (
                    "valor_pago",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Valor Pago",
                    ),
                ),
                (
                    "juros",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Juros/Multa",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pendente", "Pendente"),
                            ("Pago", "Pago"),
                            ("Atrasado", "Atrasado"),
                        ],
                        default="Pendente",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "tipo_gasto",
                    models.CharField(
                        choices=[
                            ("SIMPLES", "DAS Simples"),
                            ("FGTS", "FGTS"),
                            ("HONORARIO", "Honorário Contábil"),
                            ("INSS", "INSS"),
                            ("IR", "Imposto de Renda"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Encargo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gasto Contábil",
                "verbose_name_plural": "Encargos e Contabilidade",
            },
        ),
        migrations.CreateModel(
            name="GastoGeral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=255, verbose_name="Descrição do Item"),
                ),
                ("data_gasto", models.DateField(verbose_name="Data do Gasto")),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor Total"
                    ),
                ),
                (
                    "valor_dinheiro_pix",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Valor em Pix/Dinheiro",
                    ),
                ),
                (
                    "valor_cartao",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Valor em Cartão",
                    ),
                ),
                (
                    "forma_principal_pagamento",
                    models.CharField(
                        choices=[
                            ("PIX", "Pix"),
                            ("DINHEIRO", "Dinheiro"),
                            ("CARTAO", "Cartão"),
                        ],
                        max_length=10,
                        verbose_name="Forma Principal",
                    ),
                ),
                ("motorista", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "carro",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Carro/Veículo",
                    ),
                ),
                ("cliente", models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                "verbose_name": "Gasto Geral",
                "verbose_name_plural": "Gastos Gerais (Almoço, Material, etc.)",
            },
        ),
        migrations.CreateModel(
            name="GastoImovel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=255, verbose_name="Descrição do Gasto"),
                ),
                (
                    "valor_original",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor Original"
                    ),
                ),
                (
                    "data_vencimento",
                    models.DateField(verbose_name="Data de Vencimento"),
                ),
                (
                    "data_pagamento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Pagamento"
                    ),
                ),
                (
                    "valor_pago",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Valor Pago",
                    ),
                ),
                (
                    "juros",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Juros/Multa",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pendente", "Pendente"),
                            ("Pago", "Pago"),
                            ("Atrasado", "Atrasado"),
                        ],
                        default="Pendente",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "tipo_gasto",
                    models.CharField(
                        choices=[
                            ("IPTU", "IPTU"),
                            ("CONDO", "Condomínio (Alphaville)"),
                            ("TAXA", "Taxa de Averbação"),
                            ("ACORDO", "Acordo de Condomínio"),
                        ],
                        max_length=10,
                        verbose_name="Tipo de Gasto Imobiliário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gasto Imobiliário",
                "verbose_name_plural": "IPTU e Condomínios",
            },
        ),
        migrations.CreateModel(
            name="GastoUtilidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=255, verbose_name="Descrição do Gasto"),
                ),
                (
                    "valor_original",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor Original"
                    ),
                ),
                (
                    "data_vencimento",
                    models.DateField(verbose_name="Data de Vencimento"),
                ),
                (
                    "data_pagamento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Pagamento"
                    ),
                ),
                (
                    "valor_pago",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Valor Pago",
                    ),
                ),
                (
                    "juros",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Juros/Multa",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pendente", "Pendente"),
                            ("Pago", "Pago"),
                            ("Atrasado", "Atrasado"),
                        ],
                        default="Pendente",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "tipo_cliente",
                    models.CharField(
                        choices=[
                            ("CEL", "Celulares"),
                            ("CESAN_ALPHA", "Cesan - Alphaville"),
                            ("ESC_MARCENARIA", "Escelsa - Marcenaria"),
                            ("INT_ALPHA", "Internet - Alphaville"),
                        ],
                        max_length=50,
                        verbose_name="Cliente/Tipo de Utilidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gasto com Utilidade",
                "verbose_name_plural": "Água, Luz e Telefone",
            },
        ),
        migrations.CreateModel(
            name="GastoVeiculoConsorcio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=255, verbose_name="Descrição do Gasto"),
                ),
                (
                    "valor_original",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor Original"
                    ),
                ),
                (
                    "data_vencimento",
                    models.DateField(verbose_name="Data de Vencimento"),
                ),
                (
                    "data_pagamento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Pagamento"
                    ),
                ),
                (
                    "valor_pago",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Valor Pago",
                    ),
                ),
                (
                    "juros",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Juros/Multa",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pendente", "Pendente"),
                            ("Pago", "Pago"),
                            ("Atrasado", "Atrasado"),
                        ],
                        default="Pendente",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "tipo_gasto",
                    models.CharField(
                        choices=[
                            ("CONS", "Consórcio"),
                            ("IPVA", "IPVA"),
                            ("SEGURO", "Seguro"),
                            ("LICEN", "Licenciamento"),
                            ("OUTRO", "Outro Gasto Veicular"),
                        ],
                        max_length=10,
                        verbose_name="Tipo de Gasto",
                    ),
                ),
                (
                    "veiculo_referencia",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Veículo/Consórcio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gasto de Veículo/Consórcio",
                "verbose_name_plural": "Consórcios e Carros",
            },
        ),
        migrations.CreateModel(
            name="Imovel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "local_lote",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Local/Lote"
                    ),
                ),
                (
                    "numero_inscricao",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Nº Incrição Municipal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PagamentoFuncionario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mes_referencia", models.DateField(verbose_name="Mês de Referência")),
                ("salario_real", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "adiantamento",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "terco_ferias",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "empreitadas",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "decimo_terceiro",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "total_liquido",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Total Pago"
                    ),
                ),
            ],
            options={
                "verbose_name": "Pagamento de Funcionário",
                "verbose_name_plural": "Folha de Pagamento",
            },
        ),
        migrations.CreateModel(
            name="Pessoa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("FUNC", "Funcionário"),
                            ("ARQ", "Arquiteto/Comissionado"),
                        ],
                        max_length=4,
                    ),
                ),
                ("cargo", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "salario_base",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("data_entrada", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PrestacaoEmprestimo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=255, verbose_name="Descrição do Gasto"),
                ),
                (
                    "valor_original",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor Original"
                    ),
                ),
                (
                    "data_vencimento",
                    models.DateField(verbose_name="Data de Vencimento"),
                ),
                (
                    "data_pagamento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Pagamento"
                    ),
                ),
                (
                    "valor_pago",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Valor Pago",
                    ),
                ),
                (
                    "juros",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Juros/Multa",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pendente", "Pendente"),
                            ("Pago", "Pago"),
                            ("Atrasado", "Atrasado"),
                        ],
                        default="Pendente",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "numero_parcela",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Nº da Parcela"
                    ),
                ),
                (
                    "emprestimo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pagar.emprestimo",
                        verbose_name="Empréstimo Referência",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prestação de Empréstimo",
                "verbose_name_plural": "Prestações de Empréstimos",
            },
        ),
        migrations.DeleteModel(
            name="Pagar",
        ),
        migrations.CreateModel(
            name="GastoGasolina",
            fields=[],
            options={
                "verbose_name": "Gasto com Gasolina",
                "verbose_name_plural": "Gastos com Gasolina",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("pagar.gastogeral",),
        ),
        migrations.AddField(
            model_name="gastoimovel",
            name="imovel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="pagar.imovel",
                verbose_name="Imóvel Referência",
            ),
        ),
        migrations.AddField(
            model_name="pagamentofuncionario",
            name="funcionario",
            field=models.ForeignKey(
                limit_choices_to={"tipo": "FUNC"},
                on_delete=django.db.models.deletion.PROTECT,
                to="pagar.pessoa",
                verbose_name="Funcionário",
            ),
        ),
        migrations.AddField(
            model_name="comissaoarquiteto",
            name="arquiteto",
            field=models.ForeignKey(
                limit_choices_to={"tipo": "ARQ"},
                on_delete=django.db.models.deletion.PROTECT,
                to="pagar.pessoa",
                verbose_name="Arquiteto",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pagamentofuncionario",
            unique_together={("funcionario", "mes_referencia")},
        ),
    ]
