# Generated by Django 5.2.6 on 2025-12-06 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pagar", "0004_boleto_cheque_comissaoarquiteto_emprestimo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prestacaoemprestimo",
            name="emprestimo",
        ),
    ]
