# Generated by Django 5.2.6 on 2025-12-07 00:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagar", "0005_remove_prestacaoemprestimo_emprestimo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="boleto",
            name="valor_original",
        ),
        migrations.RemoveField(
            model_name="faturacartao",
            name="valor_original",
        ),
        migrations.RemoveField(
            model_name="gastocontabilidade",
            name="valor_original",
        ),
        migrations.RemoveField(
            model_name="gastoimovel",
            name="valor_original",
        ),
        migrations.RemoveField(
            model_name="gastoutilidade",
            name="valor_original",
        ),
        migrations.RemoveField(
            model_name="gastoveiculoconsorcio",
            name="valor_original",
        ),
        migrations.RemoveField(
            model_name="prestacaoemprestimo",
            name="valor_original",
        ),
        migrations.AddField(
            model_name="boleto",
            name="valor",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Valor",
            ),
        ),
        migrations.AddField(
            model_name="faturacartao",
            name="valor",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Valor",
            ),
        ),
        migrations.AddField(
            model_name="gastocontabilidade",
            name="valor",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Valor",
            ),
        ),
        migrations.AddField(
            model_name="gastogeral",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pendente", "Pendente"),
                    ("Pago", "Pago"),
                    ("Atrasado", "Atrasado"),
                ],
                default="Pago",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="gastoimovel",
            name="valor",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Valor",
            ),
        ),
        migrations.AddField(
            model_name="gastoutilidade",
            name="valor",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Valor",
            ),
        ),
        migrations.AddField(
            model_name="gastoveiculoconsorcio",
            name="valor",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Valor",
            ),
        ),
        migrations.AddField(
            model_name="prestacaoemprestimo",
            name="valor",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Valor",
            ),
        ),
        migrations.AlterField(
            model_name="boleto",
            name="descricao",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Descrição do Gasto"
            ),
        ),
        migrations.AlterField(
            model_name="faturacartao",
            name="descricao",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Descrição do Gasto"
            ),
        ),
        migrations.AlterField(
            model_name="gastocontabilidade",
            name="descricao",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Descrição do Gasto"
            ),
        ),
        migrations.AlterField(
            model_name="gastoimovel",
            name="descricao",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Descrição do Gasto"
            ),
        ),
        migrations.AlterField(
            model_name="gastoutilidade",
            name="descricao",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Descrição do Gasto"
            ),
        ),
        migrations.AlterField(
            model_name="gastoutilidade",
            name="tipo_cliente",
            field=models.CharField(
                choices=[
                    ("CEL", "Celulares"),
                    ("CESAN_ALPHA", "Cesan - Alphaville"),
                    ("ESC_MARCENARIA", "Escelsa - Marcenaria"),
                    ("INT_ALPHA", "Internet - Alphaville"),
                    ("CESAN_MARCENARIA", "Cesan - Marcenaria"),
                    ("ESC_ALPHA", "Escelsa - Alphaville"),
                    ("INT_MARCENARIA", "Internet - Marcenaria"),
                ],
                max_length=50,
                verbose_name="Cliente/Tipo de Utilidade",
            ),
        ),
        migrations.AlterField(
            model_name="gastoveiculoconsorcio",
            name="descricao",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Descrição do Gasto"
            ),
        ),
        migrations.AlterField(
            model_name="prestacaoemprestimo",
            name="descricao",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Descrição do Gasto"
            ),
        ),
    ]
