# Generated by Django 5.2.6 on 2025-12-07 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pagar", "0006_remove_boleto_valor_original_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gastocontabilidade",
            old_name="tipo_gasto",
            new_name="categoria",
        ),
        migrations.RenameField(
            model_name="gastoimovel",
            old_name="tipo_gasto",
            new_name="categoria",
        ),
        migrations.RenameField(
            model_name="gastoveiculoconsorcio",
            old_name="tipo_gasto",
            new_name="categoria",
        ),
    ]
