# Generated by Django 5.2.6 on 2025-12-07 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pagar", "0007_rename_tipo_gasto_gastocontabilidade_categoria_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gastocontabilidade",
            old_name="categoria",
            new_name="tipo_gasto",
        ),
        migrations.RenameField(
            model_name="gastoimovel",
            old_name="categoria",
            new_name="tipo_gasto",
        ),
        migrations.RenameField(
            model_name="gastoveiculoconsorcio",
            old_name="categoria",
            new_name="tipo_gasto",
        ),
    ]
