# Generated by Django 5.2.6 on 2025-12-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagar", "0008_rename_categoria_gastocontabilidade_tipo_gasto_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boleto",
            name="descricao",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Descrição do Gasto",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="faturacartao",
            name="descricao",
            field=models.CharField(
                blank=True,
                default="a",
                max_length=255,
                verbose_name="Descrição do Gasto",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="gastocontabilidade",
            name="descricao",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Descrição do Gasto",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="gastoimovel",
            name="descricao",
            field=models.CharField(
                blank=True,
                default=11,
                max_length=255,
                verbose_name="Descrição do Gasto",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="gastoutilidade",
            name="descricao",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Descrição do Gasto",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="gastoveiculoconsorcio",
            name="descricao",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Descrição do Gasto",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="prestacaoemprestimo",
            name="descricao",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Descrição do Gasto",
            ),
            preserve_default=False,
        ),
    ]
