# Generated by Django 5.2.6 on 2025-12-07 19:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagar", "0010_alter_boleto_juros_alter_faturacartao_juros_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boleto",
            name="valor",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                null=True,
                verbose_name="Valor",
            ),
        ),
        migrations.AlterField(
            model_name="faturacartao",
            name="valor",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                null=True,
                verbose_name="Valor",
            ),
        ),
        migrations.AlterField(
            model_name="gastocontabilidade",
            name="valor",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                null=True,
                verbose_name="Valor",
            ),
        ),
        migrations.AlterField(
            model_name="gastoimovel",
            name="valor",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                null=True,
                verbose_name="Valor",
            ),
        ),
        migrations.AlterField(
            model_name="gastoutilidade",
            name="valor",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                null=True,
                verbose_name="Valor",
            ),
        ),
        migrations.AlterField(
            model_name="gastoveiculoconsorcio",
            name="valor",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                null=True,
                verbose_name="Valor",
            ),
        ),
        migrations.AlterField(
            model_name="prestacaoemprestimo",
            name="valor",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                null=True,
                verbose_name="Valor",
            ),
        ),
    ]
