# Generated by Django 5.2.6 on 2025-12-07 19:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagar", "0011_alter_boleto_valor_alter_faturacartao_valor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boleto",
            name="juros",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                null=True,
                verbose_name="Juros/Multa",
            ),
        ),
        migrations.AlterField(
            model_name="faturacartao",
            name="juros",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                null=True,
                verbose_name="Juros/Multa",
            ),
        ),
        migrations.AlterField(
            model_name="gastocontabilidade",
            name="juros",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                null=True,
                verbose_name="Juros/Multa",
            ),
        ),
        migrations.AlterField(
            model_name="gastoimovel",
            name="juros",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                null=True,
                verbose_name="Juros/Multa",
            ),
        ),
        migrations.AlterField(
            model_name="gastoutilidade",
            name="juros",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                null=True,
                verbose_name="Juros/Multa",
            ),
        ),
        migrations.AlterField(
            model_name="gastoveiculoconsorcio",
            name="juros",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                null=True,
                verbose_name="Juros/Multa",
            ),
        ),
        migrations.AlterField(
            model_name="prestacaoemprestimo",
            name="juros",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                null=True,
                verbose_name="Juros/Multa",
            ),
        ),
    ]
