# Generated by Django 5.2.6 on 2025-12-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagar", "0012_alter_boleto_juros_alter_faturacartao_juros_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gastocontabilidade",
            name="tipo_gasto",
            field=models.CharField(
                choices=[
                    ("SIMPLES", "DAS Simples"),
                    ("FGTS", "FGTS"),
                    ("HONORARIO", "Honorário Contábil"),
                    ("INSS", "INSS"),
                    ("IR", "Imposto de Renda"),
                    ("SeguroFuncionarios", "Seguro dos Funcionarios"),
                ],
                max_length=20,
                verbose_name="Tipo de Encargo",
            ),
        ),
    ]
