# Generated by Django 5.2.6 on 2025-12-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagar", "0013_alter_gastocontabilidade_tipo_gasto"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GastoGasolina",
        ),
        migrations.CreateModel(
            name="GastoGasolina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=255, verbose_name="Descrição do Item"),
                ),
                ("data_gasto", models.DateField(verbose_name="Data do Gasto")),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor Total"
                    ),
                ),
                (
                    "carro",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Carro/Veículo",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pendente", "Pendente"),
                            ("Pago", "Pago"),
                            ("Atrasado", "Atrasado"),
                        ],
                        default="Pago",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gasto com Gasolina",
                "verbose_name_plural": "Gastos com Gasolina",
            },
        ),
    ]
