# Generated by Django 5.2.6 on 2025-12-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagar", "0014_delete_gastogasolina_gastogasolina"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gastoimovel",
            name="imovel",
        ),
        migrations.AddField(
            model_name="gastoimovel",
            name="local_lote",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Local/Lote (Referência)",
            ),
        ),
        migrations.AddField(
            model_name="gastoimovel",
            name="numero_inscricao",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Número de Inscrição"
            ),
        ),
        migrations.DeleteModel(
            name="Imovel",
        ),
    ]
