# Generated by Django 5.2.7 on 2025-12-11 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagar", "0015_remove_gastoimovel_imovel_gastoimovel_local_lote_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prestacaoemprestimo",
            name="numero_parcela",
        ),
        migrations.AddField(
            model_name="prestacaoemprestimo",
            name="prestacao",
            field=models.IntegerField(blank=True, null=True, verbose_name="Prestação"),
        ),
    ]
