# Generated by Django 5.2.7 on 2025-12-12 17:47

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funcionarios", "0004_remove_dadostrabalhistas_saldo_banco_horas"),
        ("pagar", "0016_remove_prestacaoemprestimo_numero_parcela_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FolhaPagamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_referencia", models.DateField(verbose_name="Mês de Referência")),
                (
                    "salario_real",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Salário Real/Combinado",
                    ),
                ),
                (
                    "adiantamento",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Adiantamento",
                    ),
                ),
                (
                    "ferias_terco",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="1/3 Férias",
                    ),
                ),
                (
                    "empreitada",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Empreitadas",
                    ),
                ),
                (
                    "decimo_terceiro",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="13º Salário",
                    ),
                ),
                (
                    "vale",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Vales",
                    ),
                ),
                (
                    "horas_extras_valor",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Horas Extras (R$)",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="funcionarios.funcionario",
                        verbose_name="Funcionário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pagamento de Folha",
                "verbose_name_plural": "Pagamentos de Folha",
                "ordering": ["-data_referencia", "funcionario__nome"],
            },
        ),
    ]
