# Generated by Django 5.2.6 on 2025-12-12 23:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagar", "0017_folhapagamento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gastogeral",
            name="forma_principal_pagamento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PIX", "Pix"),
                    ("DINHEIRO", "Dinheiro"),
                    ("CARTAO", "Cartão"),
                ],
                max_length=10,
                null=True,
                verbose_name="Forma de Pagamento",
            ),
        ),
        migrations.AlterField(
            model_name="gastogeral",
            name="valor_cartao",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                null=True,
                verbose_name="Valor em Cartão",
            ),
        ),
        migrations.AlterField(
            model_name="gastogeral",
            name="valor_dinheiro_pix",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                null=True,
                verbose_name="Valor em Pix/Dinheiro",
            ),
        ),
        migrations.AlterField(
            model_name="gastogeral",
            name="valor_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Valor Total",
            ),
        ),
    ]
