# Generated by Django 5.2.7 on 2025-12-13 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comissionamento", "0001_initial"),
        ("pagar", "0018_alter_gastogeral_forma_principal_pagamento_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comissaoarquiteto",
            name="arquiteto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="comissionamento.arquiteta",
                verbose_name="Arquiteta",
            ),
        ),
        migrations.AlterField(
            model_name="comissaoarquiteto",
            name="data_pagamento",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="comissaoarquiteto",
            name="valor_comissao",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
