# Generated by Django 5.2.6 on 2025-12-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagar", "0019_alter_comissaoarquiteto_arquiteto_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pessoa",
            name="tipo",
            field=models.CharField(choices=[("FUNC", "Funcionário")], max_length=4),
        ),
    ]
