# Generated by Django 5.2.7 on 2025-12-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagar", "0020_alter_pessoa_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="comissaoarquiteto",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pendente", "Pendente"),
                    ("Pago", "Pago"),
                    ("Atrasado", "Atrasado"),
                ],
                default="Pago",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="folhapagamento",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pendente", "Pendente"),
                    ("Pago", "Pago"),
                    ("Atrasado", "Atrasado"),
                ],
                default="Pendente",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
