# Generated by Django 5.2.6 on 2025-12-30 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagar", "0021_comissaoarquiteto_status_folhapagamento_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="gastogeral",
            name="tipo_pagamento",
            field=models.CharField(
                choices=[
                    ("VISTA", "À Vista (Caixa/Pix/Débito)"),
                    ("PRAZO", "A Prazo (Boleto/Crédito/Outros)"),
                ],
                default="VISTA",
                max_length=10,
                verbose_name="Classificação Gerencial",
            ),
        ),
    ]
