# Generated by Django 5.2.6 on 2025-12-31 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagar", "0022_gastogeral_tipo_pagamento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gastogeral",
            name="tipo_pagamento",
            field=models.CharField(
                choices=[("VISTA", "À Vista"), ("PRAZO", "A Prazo")],
                default="VISTA",
                max_length=10,
                verbose_name="Classificação Gerencial",
            ),
        ),
    ]
