# Generated by Django 5.2.7 on 2025-12-31 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagar", "0023_alter_gastogeral_tipo_pagamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="boleto",
            name="credor",
            field=models.CharField(
                blank=True,
                help_text="Nome da empresa ou pessoa que receberá o pagamento (Igual à planilha)",
                max_length=150,
                null=True,
                verbose_name="Credor / Fornecedor",
            ),
        ),
        migrations.AddField(
            model_name="faturacartao",
            name="credor",
            field=models.CharField(
                blank=True,
                help_text="Nome da empresa ou pessoa que receberá o pagamento (Igual à planilha)",
                max_length=150,
                null=True,
                verbose_name="Credor / Fornecedor",
            ),
        ),
        migrations.AddField(
            model_name="folhapagamento",
            name="credor",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Credor / Fornecedor",
            ),
        ),
        migrations.AddField(
            model_name="gastocontabilidade",
            name="credor",
            field=models.CharField(
                blank=True,
                help_text="Nome da empresa ou pessoa que receberá o pagamento (Igual à planilha)",
                max_length=150,
                null=True,
                verbose_name="Credor / Fornecedor",
            ),
        ),
        migrations.AddField(
            model_name="gastogeral",
            name="credor",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Credor / Fornecedor",
            ),
        ),
        migrations.AddField(
            model_name="gastoimovel",
            name="credor",
            field=models.CharField(
                blank=True,
                help_text="Nome da empresa ou pessoa que receberá o pagamento (Igual à planilha)",
                max_length=150,
                null=True,
                verbose_name="Credor / Fornecedor",
            ),
        ),
        migrations.AddField(
            model_name="gastoutilidade",
            name="credor",
            field=models.CharField(
                blank=True,
                help_text="Nome da empresa ou pessoa que receberá o pagamento (Igual à planilha)",
                max_length=150,
                null=True,
                verbose_name="Credor / Fornecedor",
            ),
        ),
        migrations.AddField(
            model_name="gastoveiculoconsorcio",
            name="credor",
            field=models.CharField(
                blank=True,
                help_text="Nome da empresa ou pessoa que receberá o pagamento (Igual à planilha)",
                max_length=150,
                null=True,
                verbose_name="Credor / Fornecedor",
            ),
        ),
        migrations.AddField(
            model_name="prestacaoemprestimo",
            name="credor",
            field=models.CharField(
                blank=True,
                help_text="Nome da empresa ou pessoa que receberá o pagamento (Igual à planilha)",
                max_length=150,
                null=True,
                verbose_name="Credor / Fornecedor",
            ),
        ),
    ]
