# Generated by Django 5.2.7 on 2025-12-31 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pagar", "0024_boleto_credor_faturacartao_credor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="folhapagamento",
            name="credor",
        ),
    ]
