# Generated by Django 5.2.6 on 2026-01-01 23:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagar", "0025_remove_folhapagamento_credor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boleto",
            name="credor",
            field=models.CharField(
                blank=True,
                help_text="Nome da empresa ou pessoa que receberá o pagamento",
                max_length=150,
                null=True,
                verbose_name="Credor / Fornecedor",
            ),
        ),
        migrations.AlterField(
            model_name="boleto",
            name="descricao",
            field=models.CharField(max_length=255, verbose_name="Descrição do Gasto"),
        ),
        migrations.AlterField(
            model_name="boleto",
            name="valor",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Valor Previsto",
            ),
        ),
        migrations.AlterField(
            model_name="faturacartao",
            name="credor",
            field=models.CharField(
                blank=True,
                help_text="Nome da empresa ou pessoa que receberá o pagamento",
                max_length=150,
                null=True,
                verbose_name="Credor / Fornecedor",
            ),
        ),
        migrations.AlterField(
            model_name="faturacartao",
            name="descricao",
            field=models.CharField(max_length=255, verbose_name="Descrição do Gasto"),
        ),
        migrations.AlterField(
            model_name="faturacartao",
            name="valor",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Valor Previsto",
            ),
        ),
        migrations.AlterField(
            model_name="gastocontabilidade",
            name="credor",
            field=models.CharField(
                blank=True,
                help_text="Nome da empresa ou pessoa que receberá o pagamento",
                max_length=150,
                null=True,
                verbose_name="Credor / Fornecedor",
            ),
        ),
        migrations.AlterField(
            model_name="gastocontabilidade",
            name="descricao",
            field=models.CharField(max_length=255, verbose_name="Descrição do Gasto"),
        ),
        migrations.AlterField(
            model_name="gastocontabilidade",
            name="valor",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Valor Previsto",
            ),
        ),
        migrations.AlterField(
            model_name="gastoimovel",
            name="credor",
            field=models.CharField(
                blank=True,
                help_text="Nome da empresa ou pessoa que receberá o pagamento",
                max_length=150,
                null=True,
                verbose_name="Credor / Fornecedor",
            ),
        ),
        migrations.AlterField(
            model_name="gastoimovel",
            name="descricao",
            field=models.CharField(max_length=255, verbose_name="Descrição do Gasto"),
        ),
        migrations.AlterField(
            model_name="gastoimovel",
            name="valor",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Valor Previsto",
            ),
        ),
        migrations.AlterField(
            model_name="gastoutilidade",
            name="credor",
            field=models.CharField(
                blank=True,
                help_text="Nome da empresa ou pessoa que receberá o pagamento",
                max_length=150,
                null=True,
                verbose_name="Credor / Fornecedor",
            ),
        ),
        migrations.AlterField(
            model_name="gastoutilidade",
            name="descricao",
            field=models.CharField(max_length=255, verbose_name="Descrição do Gasto"),
        ),
        migrations.AlterField(
            model_name="gastoutilidade",
            name="valor",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Valor Previsto",
            ),
        ),
        migrations.AlterField(
            model_name="gastoveiculoconsorcio",
            name="credor",
            field=models.CharField(
                blank=True,
                help_text="Nome da empresa ou pessoa que receberá o pagamento",
                max_length=150,
                null=True,
                verbose_name="Credor / Fornecedor",
            ),
        ),
        migrations.AlterField(
            model_name="gastoveiculoconsorcio",
            name="descricao",
            field=models.CharField(max_length=255, verbose_name="Descrição do Gasto"),
        ),
        migrations.AlterField(
            model_name="gastoveiculoconsorcio",
            name="valor",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Valor Previsto",
            ),
        ),
        migrations.AlterField(
            model_name="prestacaoemprestimo",
            name="credor",
            field=models.CharField(
                blank=True,
                help_text="Nome da empresa ou pessoa que receberá o pagamento",
                max_length=150,
                null=True,
                verbose_name="Credor / Fornecedor",
            ),
        ),
        migrations.AlterField(
            model_name="prestacaoemprestimo",
            name="descricao",
            field=models.CharField(max_length=255, verbose_name="Descrição do Gasto"),
        ),
        migrations.AlterField(
            model_name="prestacaoemprestimo",
            name="valor",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Valor Previsto",
            ),
        ),
    ]
