# Generated by Django 5.2.6 on 2026-01-02 00:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagar", "0026_alter_boleto_credor_alter_boleto_descricao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="boleto",
            name="forma_pagamento",
            field=models.CharField(
                choices=[
                    ("DINHEIRO", "Dinheiro"),
                    ("PIX", "Pix"),
                    ("DEBITO", "Cartão de Débito"),
                    ("CREDITO", "Cartão de Crédito"),
                    ("BOLETO", "Boleto"),
                    ("TRANSFERENCIA", "Transferência"),
                    ("OUTROS", "Outros"),
                ],
                default="BOLETO",
                max_length=20,
                verbose_name="Forma de Pagamento",
            ),
        ),
        migrations.AddField(
            model_name="comissaoarquiteto",
            name="forma_pagamento",
            field=models.CharField(
                choices=[
                    ("DINHEIRO", "Dinheiro"),
                    ("PIX", "Pix"),
                    ("DEBITO", "Cartão de Débito"),
                    ("CREDITO", "Cartão de Crédito"),
                    ("BOLETO", "Boleto"),
                    ("TRANSFERENCIA", "Transferência"),
                    ("OUTROS", "Outros"),
                ],
                default="PIX",
                max_length=20,
                verbose_name="Forma de Pagamento",
            ),
        ),
        migrations.AddField(
            model_name="faturacartao",
            name="forma_pagamento",
            field=models.CharField(
                choices=[
                    ("DINHEIRO", "Dinheiro"),
                    ("PIX", "Pix"),
                    ("DEBITO", "Cartão de Débito"),
                    ("CREDITO", "Cartão de Crédito"),
                    ("BOLETO", "Boleto"),
                    ("TRANSFERENCIA", "Transferência"),
                    ("OUTROS", "Outros"),
                ],
                default="BOLETO",
                max_length=20,
                verbose_name="Forma de Pagamento",
            ),
        ),
        migrations.AddField(
            model_name="folhapagamento",
            name="forma_pagamento",
            field=models.CharField(
                choices=[
                    ("DINHEIRO", "Dinheiro"),
                    ("PIX", "Pix"),
                    ("DEBITO", "Cartão de Débito"),
                    ("CREDITO", "Cartão de Crédito"),
                    ("BOLETO", "Boleto"),
                    ("TRANSFERENCIA", "Transferência"),
                    ("OUTROS", "Outros"),
                ],
                default="PIX",
                max_length=20,
                verbose_name="Forma de Pagamento",
            ),
        ),
        migrations.AddField(
            model_name="gastocontabilidade",
            name="forma_pagamento",
            field=models.CharField(
                choices=[
                    ("DINHEIRO", "Dinheiro"),
                    ("PIX", "Pix"),
                    ("DEBITO", "Cartão de Débito"),
                    ("CREDITO", "Cartão de Crédito"),
                    ("BOLETO", "Boleto"),
                    ("TRANSFERENCIA", "Transferência"),
                    ("OUTROS", "Outros"),
                ],
                default="BOLETO",
                max_length=20,
                verbose_name="Forma de Pagamento",
            ),
        ),
        migrations.AddField(
            model_name="gastogeral",
            name="forma_pagamento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DINHEIRO", "Dinheiro"),
                    ("PIX", "Pix"),
                    ("DEBITO", "Cartão de Débito"),
                    ("CREDITO", "Cartão de Crédito"),
                    ("BOLETO", "Boleto"),
                    ("TRANSFERENCIA", "Transferência"),
                    ("OUTROS", "Outros"),
                ],
                default="PIX",
                max_length=20,
                null=True,
                verbose_name="Forma de Pagamento",
            ),
        ),
        migrations.AddField(
            model_name="gastoimovel",
            name="forma_pagamento",
            field=models.CharField(
                choices=[
                    ("DINHEIRO", "Dinheiro"),
                    ("PIX", "Pix"),
                    ("DEBITO", "Cartão de Débito"),
                    ("CREDITO", "Cartão de Crédito"),
                    ("BOLETO", "Boleto"),
                    ("TRANSFERENCIA", "Transferência"),
                    ("OUTROS", "Outros"),
                ],
                default="BOLETO",
                max_length=20,
                verbose_name="Forma de Pagamento",
            ),
        ),
        migrations.AddField(
            model_name="gastoutilidade",
            name="forma_pagamento",
            field=models.CharField(
                choices=[
                    ("DINHEIRO", "Dinheiro"),
                    ("PIX", "Pix"),
                    ("DEBITO", "Cartão de Débito"),
                    ("CREDITO", "Cartão de Crédito"),
                    ("BOLETO", "Boleto"),
                    ("TRANSFERENCIA", "Transferência"),
                    ("OUTROS", "Outros"),
                ],
                default="BOLETO",
                max_length=20,
                verbose_name="Forma de Pagamento",
            ),
        ),
        migrations.AddField(
            model_name="gastoveiculoconsorcio",
            name="forma_pagamento",
            field=models.CharField(
                choices=[
                    ("DINHEIRO", "Dinheiro"),
                    ("PIX", "Pix"),
                    ("DEBITO", "Cartão de Débito"),
                    ("CREDITO", "Cartão de Crédito"),
                    ("BOLETO", "Boleto"),
                    ("TRANSFERENCIA", "Transferência"),
                    ("OUTROS", "Outros"),
                ],
                default="BOLETO",
                max_length=20,
                verbose_name="Forma de Pagamento",
            ),
        ),
        migrations.AddField(
            model_name="prestacaoemprestimo",
            name="forma_pagamento",
            field=models.CharField(
                choices=[
                    ("DINHEIRO", "Dinheiro"),
                    ("PIX", "Pix"),
                    ("DEBITO", "Cartão de Débito"),
                    ("CREDITO", "Cartão de Crédito"),
                    ("BOLETO", "Boleto"),
                    ("TRANSFERENCIA", "Transferência"),
                    ("OUTROS", "Outros"),
                ],
                default="BOLETO",
                max_length=20,
                verbose_name="Forma de Pagamento",
            ),
        ),
        migrations.AlterField(
            model_name="boleto",
            name="credor",
            field=models.CharField(
                blank=True,
                help_text="Nome da empresa ou pessoa que receberá o pagamento (Igual à planilha)",
                max_length=150,
                null=True,
                verbose_name="Credor / Fornecedor",
            ),
        ),
        migrations.AlterField(
            model_name="boleto",
            name="descricao",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Descrição do Gasto"
            ),
        ),
        migrations.AlterField(
            model_name="boleto",
            name="valor",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                null=True,
                verbose_name="Valor",
            ),
        ),
        migrations.AlterField(
            model_name="faturacartao",
            name="credor",
            field=models.CharField(
                blank=True,
                help_text="Nome da empresa ou pessoa que receberá o pagamento (Igual à planilha)",
                max_length=150,
                null=True,
                verbose_name="Credor / Fornecedor",
            ),
        ),
        migrations.AlterField(
            model_name="faturacartao",
            name="descricao",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Descrição do Gasto"
            ),
        ),
        migrations.AlterField(
            model_name="faturacartao",
            name="valor",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                null=True,
                verbose_name="Valor",
            ),
        ),
        migrations.AlterField(
            model_name="gastocontabilidade",
            name="credor",
            field=models.CharField(
                blank=True,
                help_text="Nome da empresa ou pessoa que receberá o pagamento (Igual à planilha)",
                max_length=150,
                null=True,
                verbose_name="Credor / Fornecedor",
            ),
        ),
        migrations.AlterField(
            model_name="gastocontabilidade",
            name="descricao",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Descrição do Gasto"
            ),
        ),
        migrations.AlterField(
            model_name="gastocontabilidade",
            name="valor",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                null=True,
                verbose_name="Valor",
            ),
        ),
        migrations.AlterField(
            model_name="gastoimovel",
            name="credor",
            field=models.CharField(
                blank=True,
                help_text="Nome da empresa ou pessoa que receberá o pagamento (Igual à planilha)",
                max_length=150,
                null=True,
                verbose_name="Credor / Fornecedor",
            ),
        ),
        migrations.AlterField(
            model_name="gastoimovel",
            name="descricao",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Descrição do Gasto"
            ),
        ),
        migrations.AlterField(
            model_name="gastoimovel",
            name="valor",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                null=True,
                verbose_name="Valor",
            ),
        ),
        migrations.AlterField(
            model_name="gastoutilidade",
            name="credor",
            field=models.CharField(
                blank=True,
                help_text="Nome da empresa ou pessoa que receberá o pagamento (Igual à planilha)",
                max_length=150,
                null=True,
                verbose_name="Credor / Fornecedor",
            ),
        ),
        migrations.AlterField(
            model_name="gastoutilidade",
            name="descricao",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Descrição do Gasto"
            ),
        ),
        migrations.AlterField(
            model_name="gastoutilidade",
            name="valor",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                null=True,
                verbose_name="Valor",
            ),
        ),
        migrations.AlterField(
            model_name="gastoveiculoconsorcio",
            name="credor",
            field=models.CharField(
                blank=True,
                help_text="Nome da empresa ou pessoa que receberá o pagamento (Igual à planilha)",
                max_length=150,
                null=True,
                verbose_name="Credor / Fornecedor",
            ),
        ),
        migrations.AlterField(
            model_name="gastoveiculoconsorcio",
            name="descricao",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Descrição do Gasto"
            ),
        ),
        migrations.AlterField(
            model_name="gastoveiculoconsorcio",
            name="valor",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                null=True,
                verbose_name="Valor",
            ),
        ),
        migrations.AlterField(
            model_name="prestacaoemprestimo",
            name="credor",
            field=models.CharField(
                blank=True,
                help_text="Nome da empresa ou pessoa que receberá o pagamento (Igual à planilha)",
                max_length=150,
                null=True,
                verbose_name="Credor / Fornecedor",
            ),
        ),
        migrations.AlterField(
            model_name="prestacaoemprestimo",
            name="descricao",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Descrição do Gasto"
            ),
        ),
        migrations.AlterField(
            model_name="prestacaoemprestimo",
            name="valor",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                null=True,
                verbose_name="Valor",
            ),
        ),
    ]
