# Generated by Django 5.2.6 on 2026-01-06 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagar", "0028_boleto_banco_origem_boleto_movimento_banco_and_more"),
        ("receber", "0013_receber_banco_destino_receber_movimento_banco_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faturacartao",
            name="data_pagamento",
        ),
        migrations.RemoveField(
            model_name="faturacartao",
            name="juros",
        ),
        migrations.RemoveField(
            model_name="faturacartao",
            name="valor_pago",
        ),
        migrations.RemoveField(
            model_name="gastocontabilidade",
            name="data_pagamento",
        ),
        migrations.RemoveField(
            model_name="gastocontabilidade",
            name="juros",
        ),
        migrations.RemoveField(
            model_name="gastocontabilidade",
            name="valor_pago",
        ),
        migrations.RemoveField(
            model_name="gastoimovel",
            name="data_pagamento",
        ),
        migrations.RemoveField(
            model_name="gastoimovel",
            name="juros",
        ),
        migrations.RemoveField(
            model_name="gastoimovel",
            name="valor_pago",
        ),
        migrations.RemoveField(
            model_name="gastoutilidade",
            name="data_pagamento",
        ),
        migrations.RemoveField(
            model_name="gastoutilidade",
            name="juros",
        ),
        migrations.RemoveField(
            model_name="gastoutilidade",
            name="valor_pago",
        ),
        migrations.RemoveField(
            model_name="prestacaoemprestimo",
            name="data_pagamento",
        ),
        migrations.RemoveField(
            model_name="prestacaoemprestimo",
            name="juros",
        ),
        migrations.RemoveField(
            model_name="prestacaoemprestimo",
            name="valor_pago",
        ),
        migrations.AlterField(
            model_name="boleto",
            name="banco_origem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="receber.banco",
                verbose_name="Conta Bancária",
            ),
        ),
        migrations.AlterField(
            model_name="boleto",
            name="data_pagamento",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Pagamento Real"
            ),
        ),
        migrations.AlterField(
            model_name="boleto",
            name="data_vencimento",
            field=models.DateField(verbose_name="Data de Vencimento / Pagamento"),
        ),
        migrations.AlterField(
            model_name="boleto",
            name="valor_pago",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Valor Pago Real",
            ),
        ),
        migrations.AlterField(
            model_name="faturacartao",
            name="banco_origem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="receber.banco",
                verbose_name="Conta Bancária",
            ),
        ),
        migrations.AlterField(
            model_name="faturacartao",
            name="data_vencimento",
            field=models.DateField(verbose_name="Data de Vencimento / Pagamento"),
        ),
        migrations.AlterField(
            model_name="gastocontabilidade",
            name="banco_origem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="receber.banco",
                verbose_name="Conta Bancária",
            ),
        ),
        migrations.AlterField(
            model_name="gastocontabilidade",
            name="data_vencimento",
            field=models.DateField(verbose_name="Data de Vencimento / Pagamento"),
        ),
        migrations.AlterField(
            model_name="gastoimovel",
            name="banco_origem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="receber.banco",
                verbose_name="Conta Bancária",
            ),
        ),
        migrations.AlterField(
            model_name="gastoimovel",
            name="data_vencimento",
            field=models.DateField(verbose_name="Data de Vencimento / Pagamento"),
        ),
        migrations.AlterField(
            model_name="gastoutilidade",
            name="banco_origem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="receber.banco",
                verbose_name="Conta Bancária",
            ),
        ),
        migrations.AlterField(
            model_name="gastoutilidade",
            name="data_vencimento",
            field=models.DateField(verbose_name="Data de Vencimento / Pagamento"),
        ),
        migrations.AlterField(
            model_name="gastoveiculoconsorcio",
            name="banco_origem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="receber.banco",
                verbose_name="Conta Bancária",
            ),
        ),
        migrations.AlterField(
            model_name="gastoveiculoconsorcio",
            name="data_pagamento",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Pagamento Real"
            ),
        ),
        migrations.AlterField(
            model_name="gastoveiculoconsorcio",
            name="data_vencimento",
            field=models.DateField(verbose_name="Data de Vencimento / Pagamento"),
        ),
        migrations.AlterField(
            model_name="gastoveiculoconsorcio",
            name="valor_pago",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Valor Pago Real",
            ),
        ),
        migrations.AlterField(
            model_name="prestacaoemprestimo",
            name="banco_origem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="receber.banco",
                verbose_name="Conta Bancária",
            ),
        ),
        migrations.AlterField(
            model_name="prestacaoemprestimo",
            name="data_vencimento",
            field=models.DateField(verbose_name="Data de Vencimento / Pagamento"),
        ),
    ]
