# Generated by Django 5.2.7 on 2026-01-07 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagar", "0030_boleto_deleted_at_boleto_is_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gastogasolina",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data da Exclusão"
            ),
        ),
        migrations.AddField(
            model_name="gastogasolina",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Está na Lixeira?"),
        ),
        migrations.AddField(
            model_name="gastogeral",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data da Exclusão"
            ),
        ),
        migrations.AddField(
            model_name="gastogeral",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Está na Lixeira?"),
        ),
    ]
