# Generated by Django 5.2.7 on 2026-01-07 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagar", "0031_gastogasolina_deleted_at_gastogasolina_is_deleted_and_more"),
        (
            "receber",
            "0014_movimentobanco_deleted_at_movimentobanco_is_deleted_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="cheque",
            name="banco_origem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="receber.banco",
                verbose_name="Conta de Saída",
            ),
        ),
        migrations.AddField(
            model_name="cheque",
            name="movimento_banco",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cheque_origem",
                to="receber.movimentobanco",
            ),
        ),
        migrations.AddField(
            model_name="cheque",
            name="movimento_caixa",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cheque_origem_origem",
                to="receber.caixadiario",
            ),
        ),
    ]
