# Generated by Django 5.2.7 on 2026-01-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagar", "0033_gastogeral_banco_origem_gastogeral_movimento_banco_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="boleto",
            name="parcelamento_uuid",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="cheque",
            name="parcelamento_uuid",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="comissaoarquiteto",
            name="parcelamento_uuid",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="faturacartao",
            name="parcelamento_uuid",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="folhapagamento",
            name="parcelamento_uuid",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="gastocontabilidade",
            name="parcelamento_uuid",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="gastoimovel",
            name="parcelamento_uuid",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="gastoutilidade",
            name="parcelamento_uuid",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="gastoveiculoconsorcio",
            name="parcelamento_uuid",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="prestacaoemprestimo",
            name="parcelamento_uuid",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
