# Generated by Django 5.2.7 on 2026-01-10 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comissionamento", "0007_remove_contratort_data_pagamento_and_more"),
        ("pagar", "0034_boleto_parcelamento_uuid_cheque_parcelamento_uuid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comissaoarquiteto",
            name="contrato_rt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="comissoes_pagar",
                to="comissionamento.contratort",
                verbose_name="Contrato RT Vinculado",
            ),
        ),
    ]
