# Generated by Django 5.2.7 on 2026-01-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagar", "0035_comissaoarquiteto_contrato_rt"),
    ]

    operations = [
        migrations.AddField(
            model_name="comissaoarquiteto",
            name="data_vencimento",
            field=models.DateField(
                default="2024-01-01", verbose_name="Data de Vencimento / Previsão"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comissaoarquiteto",
            name="valor_pago",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Valor Pago Real",
            ),
        ),
        migrations.AlterField(
            model_name="comissaoarquiteto",
            name="data_pagamento",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data do Pagamento Real"
            ),
        ),
        migrations.AlterField(
            model_name="comissaoarquiteto",
            name="observacoes",
            field=models.TextField(blank=True, null=True, verbose_name="Observações"),
        ),
        migrations.AlterField(
            model_name="comissaoarquiteto",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pendente", "Pendente"),
                    ("Pago", "Pago"),
                    ("Atrasado", "Atrasado"),
                ],
                default="Pendente",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="comissaoarquiteto",
            name="valor_comissao",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Valor da Comissão"
            ),
        ),
    ]
