# Generated by Django 5.2.7 on 2026-01-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagar", "0036_comissaoarquiteto_data_vencimento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="folhapagamento",
            name="referencia_holerite",
            field=models.CharField(
                blank=True,
                default="30d",
                max_length=20,
                null=True,
                verbose_name="Referência (ex: 30d)",
            ),
        ),
    ]
