# Generated by Django 5.2.6 on 2026-01-15 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comissionamento", "0007_remove_contratort_data_pagamento_and_more"),
        ("pagar", "0038_emprestimo_deleted_at_emprestimo_is_deleted"),
        ("receber", "0018_caixadiario_deleted_at_caixadiario_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boleto",
            name="banco_origem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="receber.banco",
                verbose_name="Conta Bancária",
            ),
        ),
        migrations.AlterField(
            model_name="boleto",
            name="data_pagamento",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data do Pagamento"
            ),
        ),
        migrations.AlterField(
            model_name="boleto",
            name="data_vencimento",
            field=models.DateField(verbose_name="Data de Vencimento"),
        ),
        migrations.AlterField(
            model_name="boleto",
            name="movimento_banco",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_origem",
                to="receber.movimentobanco",
            ),
        ),
        migrations.AlterField(
            model_name="boleto",
            name="movimento_caixa",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_origem",
                to="receber.caixadiario",
            ),
        ),
        migrations.AlterField(
            model_name="boleto",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pendente", "Pendente"),
                    ("Pago", "Pago"),
                    ("Atrasado", "Atrasado"),
                ],
                db_index=True,
                default="Pendente",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="boleto",
            name="valor_pago",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Valor Pago",
            ),
        ),
        migrations.AlterField(
            model_name="cheque",
            name="banco_origem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="receber.banco",
                verbose_name="Conta de Saída",
            ),
        ),
        migrations.AlterField(
            model_name="cheque",
            name="movimento_banco",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cheque_origem",
                to="receber.movimentobanco",
            ),
        ),
        migrations.AlterField(
            model_name="cheque",
            name="movimento_caixa",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cheque_origem_origem",
                to="receber.caixadiario",
            ),
        ),
        migrations.AlterField(
            model_name="cheque",
            name="numero_cheque",
            field=models.CharField(max_length=20, verbose_name="Nº do Cheque"),
        ),
        migrations.AlterField(
            model_name="comissaoarquiteto",
            name="banco_origem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="receber.banco",
                verbose_name="Conta de Saída",
            ),
        ),
        migrations.AlterField(
            model_name="comissaoarquiteto",
            name="contrato_rt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="comissoes_pagar",
                to="comissionamento.contratort",
                verbose_name="Contrato RT Vinculado",
            ),
        ),
        migrations.AlterField(
            model_name="comissaoarquiteto",
            name="movimento_banco",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="comissao_arquiteto_origem",
                to="receber.movimentobanco",
            ),
        ),
        migrations.AlterField(
            model_name="comissaoarquiteto",
            name="movimento_caixa",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="comissao_arquiteto_origem",
                to="receber.caixadiario",
            ),
        ),
        migrations.AlterField(
            model_name="faturacartao",
            name="banco_origem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="receber.banco",
                verbose_name="Conta Bancária",
            ),
        ),
        migrations.AlterField(
            model_name="faturacartao",
            name="data_vencimento",
            field=models.DateField(verbose_name="Data de Vencimento"),
        ),
        migrations.AlterField(
            model_name="faturacartao",
            name="movimento_banco",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_origem",
                to="receber.movimentobanco",
            ),
        ),
        migrations.AlterField(
            model_name="faturacartao",
            name="movimento_caixa",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_origem",
                to="receber.caixadiario",
            ),
        ),
        migrations.AlterField(
            model_name="faturacartao",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pendente", "Pendente"),
                    ("Pago", "Pago"),
                    ("Atrasado", "Atrasado"),
                ],
                db_index=True,
                default="Pendente",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="folhapagamento",
            name="banco_origem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="receber.banco",
                verbose_name="Conta de Saída",
            ),
        ),
        migrations.AlterField(
            model_name="folhapagamento",
            name="movimento_banco",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="folha_pagamento_origem",
                to="receber.movimentobanco",
            ),
        ),
        migrations.AlterField(
            model_name="folhapagamento",
            name="movimento_caixa",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="folha_pagamento_origem",
                to="receber.caixadiario",
            ),
        ),
        migrations.AlterField(
            model_name="gastocontabilidade",
            name="banco_origem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="receber.banco",
                verbose_name="Conta Bancária",
            ),
        ),
        migrations.AlterField(
            model_name="gastocontabilidade",
            name="data_vencimento",
            field=models.DateField(verbose_name="Data de Vencimento"),
        ),
        migrations.AlterField(
            model_name="gastocontabilidade",
            name="movimento_banco",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_origem",
                to="receber.movimentobanco",
            ),
        ),
        migrations.AlterField(
            model_name="gastocontabilidade",
            name="movimento_caixa",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_origem",
                to="receber.caixadiario",
            ),
        ),
        migrations.AlterField(
            model_name="gastocontabilidade",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pendente", "Pendente"),
                    ("Pago", "Pago"),
                    ("Atrasado", "Atrasado"),
                ],
                db_index=True,
                default="Pendente",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="gastogasolina",
            name="banco_origem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="receber.banco",
                verbose_name="Conta de Saída",
            ),
        ),
        migrations.AlterField(
            model_name="gastogasolina",
            name="movimento_banco",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="gasto_gasolina_origem",
                to="receber.movimentobanco",
            ),
        ),
        migrations.AlterField(
            model_name="gastogasolina",
            name="movimento_caixa",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="gasto_gasolina_origem",
                to="receber.caixadiario",
            ),
        ),
        migrations.AlterField(
            model_name="gastogeral",
            name="banco_origem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="receber.banco",
                verbose_name="Conta de Saída",
            ),
        ),
        migrations.AlterField(
            model_name="gastogeral",
            name="movimento_banco",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="gasto_geral_origem",
                to="receber.movimentobanco",
            ),
        ),
        migrations.AlterField(
            model_name="gastogeral",
            name="movimento_caixa",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="gasto_geral_origem",
                to="receber.caixadiario",
            ),
        ),
        migrations.AlterField(
            model_name="gastoimovel",
            name="banco_origem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="receber.banco",
                verbose_name="Conta Bancária",
            ),
        ),
        migrations.AlterField(
            model_name="gastoimovel",
            name="data_vencimento",
            field=models.DateField(verbose_name="Data de Vencimento"),
        ),
        migrations.AlterField(
            model_name="gastoimovel",
            name="movimento_banco",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_origem",
                to="receber.movimentobanco",
            ),
        ),
        migrations.AlterField(
            model_name="gastoimovel",
            name="movimento_caixa",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_origem",
                to="receber.caixadiario",
            ),
        ),
        migrations.AlterField(
            model_name="gastoimovel",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pendente", "Pendente"),
                    ("Pago", "Pago"),
                    ("Atrasado", "Atrasado"),
                ],
                db_index=True,
                default="Pendente",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="gastoutilidade",
            name="banco_origem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="receber.banco",
                verbose_name="Conta Bancária",
            ),
        ),
        migrations.AlterField(
            model_name="gastoutilidade",
            name="data_vencimento",
            field=models.DateField(verbose_name="Data de Vencimento"),
        ),
        migrations.AlterField(
            model_name="gastoutilidade",
            name="movimento_banco",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_origem",
                to="receber.movimentobanco",
            ),
        ),
        migrations.AlterField(
            model_name="gastoutilidade",
            name="movimento_caixa",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_origem",
                to="receber.caixadiario",
            ),
        ),
        migrations.AlterField(
            model_name="gastoutilidade",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pendente", "Pendente"),
                    ("Pago", "Pago"),
                    ("Atrasado", "Atrasado"),
                ],
                db_index=True,
                default="Pendente",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="gastoveiculoconsorcio",
            name="banco_origem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="receber.banco",
                verbose_name="Conta Bancária",
            ),
        ),
        migrations.AlterField(
            model_name="gastoveiculoconsorcio",
            name="data_vencimento",
            field=models.DateField(verbose_name="Data de Vencimento"),
        ),
        migrations.AlterField(
            model_name="gastoveiculoconsorcio",
            name="movimento_banco",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_origem",
                to="receber.movimentobanco",
            ),
        ),
        migrations.AlterField(
            model_name="gastoveiculoconsorcio",
            name="movimento_caixa",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_origem",
                to="receber.caixadiario",
            ),
        ),
        migrations.AlterField(
            model_name="gastoveiculoconsorcio",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pendente", "Pendente"),
                    ("Pago", "Pago"),
                    ("Atrasado", "Atrasado"),
                ],
                db_index=True,
                default="Pendente",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="prestacaoemprestimo",
            name="banco_origem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="receber.banco",
                verbose_name="Conta Bancária",
            ),
        ),
        migrations.AlterField(
            model_name="prestacaoemprestimo",
            name="data_vencimento",
            field=models.DateField(verbose_name="Data de Vencimento"),
        ),
        migrations.AlterField(
            model_name="prestacaoemprestimo",
            name="movimento_banco",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_origem",
                to="receber.movimentobanco",
            ),
        ),
        migrations.AlterField(
            model_name="prestacaoemprestimo",
            name="movimento_caixa",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_origem",
                to="receber.caixadiario",
            ),
        ),
        migrations.AlterField(
            model_name="prestacaoemprestimo",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pendente", "Pendente"),
                    ("Pago", "Pago"),
                    ("Atrasado", "Atrasado"),
                ],
                db_index=True,
                default="Pendente",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
