# Generated by Django 5.2.6 on 2026-01-16 18:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagar", "0039_alter_boleto_banco_origem_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParcelamentoPagar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Está na Lixeira?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data da Exclusão"
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        max_length=255, verbose_name="Descrição do Parcelamento"
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "valor_total_original",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("qtd_parcelas", models.IntegerField(default=1)),
            ],
            options={
                "verbose_name": "Parcelamento (A Pagar)",
                "verbose_name_plural": "Gestão de Parcelamentos",
                "ordering": ["-data_criacao"],
            },
        ),
        migrations.RemoveField(
            model_name="boleto",
            name="parcelamento_uuid",
        ),
        migrations.RemoveField(
            model_name="cheque",
            name="parcelamento_uuid",
        ),
        migrations.RemoveField(
            model_name="comissaoarquiteto",
            name="parcelamento_uuid",
        ),
        migrations.RemoveField(
            model_name="faturacartao",
            name="parcelamento_uuid",
        ),
        migrations.RemoveField(
            model_name="folhapagamento",
            name="parcelamento_uuid",
        ),
        migrations.RemoveField(
            model_name="gastocontabilidade",
            name="parcelamento_uuid",
        ),
        migrations.RemoveField(
            model_name="gastoimovel",
            name="parcelamento_uuid",
        ),
        migrations.RemoveField(
            model_name="gastoutilidade",
            name="parcelamento_uuid",
        ),
        migrations.RemoveField(
            model_name="gastoveiculoconsorcio",
            name="parcelamento_uuid",
        ),
        migrations.RemoveField(
            model_name="prestacaoemprestimo",
            name="parcelamento_uuid",
        ),
        migrations.AddField(
            model_name="boleto",
            name="parcelamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parcelas_%(class)s",
                to="pagar.parcelamentopagar",
                verbose_name="Vínculo de Parcelamento",
            ),
        ),
        migrations.AddField(
            model_name="cheque",
            name="parcelamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parcelas_%(class)s",
                to="pagar.parcelamentopagar",
                verbose_name="Vínculo de Parcelamento",
            ),
        ),
        migrations.AddField(
            model_name="comissaoarquiteto",
            name="parcelamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parcelas_%(class)s",
                to="pagar.parcelamentopagar",
                verbose_name="Vínculo de Parcelamento",
            ),
        ),
        migrations.AddField(
            model_name="faturacartao",
            name="parcelamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parcelas_%(class)s",
                to="pagar.parcelamentopagar",
                verbose_name="Vínculo de Parcelamento",
            ),
        ),
        migrations.AddField(
            model_name="folhapagamento",
            name="parcelamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parcelas_%(class)s",
                to="pagar.parcelamentopagar",
                verbose_name="Vínculo de Parcelamento",
            ),
        ),
        migrations.AddField(
            model_name="gastocontabilidade",
            name="parcelamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parcelas_%(class)s",
                to="pagar.parcelamentopagar",
                verbose_name="Vínculo de Parcelamento",
            ),
        ),
        migrations.AddField(
            model_name="gastoimovel",
            name="parcelamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parcelas_%(class)s",
                to="pagar.parcelamentopagar",
                verbose_name="Vínculo de Parcelamento",
            ),
        ),
        migrations.AddField(
            model_name="gastoutilidade",
            name="parcelamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parcelas_%(class)s",
                to="pagar.parcelamentopagar",
                verbose_name="Vínculo de Parcelamento",
            ),
        ),
        migrations.AddField(
            model_name="gastoveiculoconsorcio",
            name="parcelamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parcelas_%(class)s",
                to="pagar.parcelamentopagar",
                verbose_name="Vínculo de Parcelamento",
            ),
        ),
        migrations.AddField(
            model_name="prestacaoemprestimo",
            name="parcelamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parcelas_%(class)s",
                to="pagar.parcelamentopagar",
                verbose_name="Vínculo de Parcelamento",
            ),
        ),
    ]
