# Generated by Django 5.2.6 on 2026-01-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagar", "0040_parcelamentopagar_remove_boleto_parcelamento_uuid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gastogasolina",
            name="forma_pagamento",
            field=models.CharField(
                choices=[
                    ("DINHEIRO", "Dinheiro"),
                    ("PIX", "Pix"),
                    ("DEBITO", "Cartão de Débito"),
                    ("CREDITO", "Cartão de Crédito"),
                    ("BOLETO", "Boleto"),
                    ("TRANSFERENCIA", "Transferência"),
                    ("OUTROS", "Outros"),
                ],
                default="PIX",
                max_length=20,
                verbose_name="Forma de Pagamento",
            ),
        ),
    ]
