# Generated by Django 5.2.6 on 2026-01-17 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagar", "0041_gastogasolina_forma_pagamento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cheque",
            name="status",
            field=models.CharField(
                choices=[
                    ("EMI", "Emitido"),
                    ("Pago", "Compensado"),
                    ("DEV", "Devolvido"),
                    ("CAN", "Cancelado"),
                ],
                default="EMI",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
