# Generated by Django 5.2.6 on 2026-01-18 20:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagar", "0042_alter_cheque_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="folhapagamento",
            name="val_ferias",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Valor Férias",
            ),
        ),
    ]
