# Generated by Django 5.2.6 on 2026-01-23 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funcionarios", "0007_funcionario_deleted_at_funcionario_is_deleted"),
        ("pagar", "0043_folhapagamento_val_ferias"),
        ("receber", "0018_caixadiario_deleted_at_caixadiario_is_deleted"),
    ]

    operations = [
        migrations.CreateModel(
            name="GastoAlmoco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Está na Lixeira?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data da Exclusão"
                    ),
                ),
                (
                    "restaurante",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Restaurante/Local",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Descrição (Opcional)",
                    ),
                ),
                ("data_gasto", models.DateField(verbose_name="Data do Almoço")),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor Total"
                    ),
                ),
                (
                    "forma_pagamento",
                    models.CharField(
                        choices=[
                            ("DINHEIRO", "Dinheiro"),
                            ("PIX", "Pix"),
                            ("DEBITO", "Cartão de Débito"),
                            ("CREDITO", "Cartão de Crédito"),
                            ("BOLETO", "Boleto"),
                            ("TRANSFERENCIA", "Transferência"),
                            ("OUTROS", "Outros"),
                        ],
                        default="PIX",
                        max_length=20,
                        verbose_name="Forma de Pagamento",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pendente", "Pendente"),
                            ("Pago", "Pago"),
                            ("Atrasado", "Atrasado"),
                        ],
                        default="Pago",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "banco_origem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="receber.banco",
                        verbose_name="Conta de Saída",
                    ),
                ),
                (
                    "funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="funcionarios.funcionario",
                        verbose_name="Funcionário",
                    ),
                ),
                (
                    "movimento_banco",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gasto_almoco_origem",
                        to="receber.movimentobanco",
                    ),
                ),
                (
                    "movimento_caixa",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gasto_almoco_origem",
                        to="receber.caixadiario",
                    ),
                ),
                (
                    "parcelamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parcelas_%(class)s",
                        to="pagar.parcelamentopagar",
                        verbose_name="Vínculo de Parcelamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gasto com Almoço",
                "verbose_name_plural": "Almoços de Funcionários",
            },
        ),
    ]
