# Generated by Django 5.2.6 on 2026-01-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagar", "0044_gastoalmoco"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gastoalmoco",
            name="restaurante",
        ),
        migrations.AddField(
            model_name="gastoalmoco",
            name="observacoes",
            field=models.TextField(blank=True, null=True, verbose_name="Observações"),
        ),
    ]
