# Generated by Django 5.2.6 on 2026-01-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagar", "0045_remove_gastoalmoco_restaurante_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gastoalmoco",
            name="origem_pagamento",
            field=models.CharField(
                choices=[("BANCO", "Banco"), ("CAIXA", "Caixa")],
                default="BANCO",
                max_length=10,
                verbose_name="Origem do Pagamento",
            ),
        ),
    ]
