# Generated by Django 5.2.6 on 2026-01-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagar", "0046_gastoalmoco_origem_pagamento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gastoalmoco",
            name="descricao",
            field=models.CharField(
                blank=True,
                default="Almoço",
                max_length=255,
                null=True,
                verbose_name="Descrição (Opcional)",
            ),
        ),
    ]
