# Generated by Django 5.2.6 on 2026-01-27 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagar", "0047_alter_gastoalmoco_descricao"),
        ("receber", "0018_caixadiario_deleted_at_caixadiario_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boleto",
            name="banco_origem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="receber.banco",
                verbose_name="Conta Bancária",
            ),
        ),
        migrations.AlterField(
            model_name="boleto",
            name="movimento_banco",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_origem",
                to="receber.movimentobanco",
            ),
        ),
        migrations.AlterField(
            model_name="comissaoarquiteto",
            name="banco_origem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="receber.banco",
                verbose_name="Conta de Saída",
            ),
        ),
        migrations.AlterField(
            model_name="comissaoarquiteto",
            name="movimento_banco",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="comissao_arquiteto_origem",
                to="receber.movimentobanco",
            ),
        ),
        migrations.AlterField(
            model_name="faturacartao",
            name="banco_origem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="receber.banco",
                verbose_name="Conta Bancária",
            ),
        ),
        migrations.AlterField(
            model_name="faturacartao",
            name="movimento_banco",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_origem",
                to="receber.movimentobanco",
            ),
        ),
        migrations.AlterField(
            model_name="gastocontabilidade",
            name="banco_origem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="receber.banco",
                verbose_name="Conta Bancária",
            ),
        ),
        migrations.AlterField(
            model_name="gastocontabilidade",
            name="movimento_banco",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_origem",
                to="receber.movimentobanco",
            ),
        ),
        migrations.AlterField(
            model_name="gastoimovel",
            name="banco_origem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="receber.banco",
                verbose_name="Conta Bancária",
            ),
        ),
        migrations.AlterField(
            model_name="gastoimovel",
            name="movimento_banco",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_origem",
                to="receber.movimentobanco",
            ),
        ),
        migrations.AlterField(
            model_name="gastoutilidade",
            name="banco_origem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="receber.banco",
                verbose_name="Conta Bancária",
            ),
        ),
        migrations.AlterField(
            model_name="gastoutilidade",
            name="movimento_banco",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_origem",
                to="receber.movimentobanco",
            ),
        ),
        migrations.AlterField(
            model_name="gastoveiculoconsorcio",
            name="banco_origem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="receber.banco",
                verbose_name="Conta Bancária",
            ),
        ),
        migrations.AlterField(
            model_name="gastoveiculoconsorcio",
            name="movimento_banco",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_origem",
                to="receber.movimentobanco",
            ),
        ),
        migrations.AlterField(
            model_name="prestacaoemprestimo",
            name="banco_origem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="receber.banco",
                verbose_name="Conta Bancária",
            ),
        ),
        migrations.AlterField(
            model_name="prestacaoemprestimo",
            name="movimento_banco",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_origem",
                to="receber.movimentobanco",
            ),
        ),
    ]
