# Generated by Django 5.2.6 on 2026-03-07 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagar", "0048_alter_boleto_banco_origem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gastogasolina",
            name="parcelamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parcelas_%(class)s",
                to="pagar.parcelamentopagar",
                verbose_name="Vínculo de Parcelamento",
            ),
        ),
        migrations.AddField(
            model_name="gastogeral",
            name="parcelamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parcelas_%(class)s",
                to="pagar.parcelamentopagar",
                verbose_name="Vínculo de Parcelamento",
            ),
        ),
    ]
