# Generated by Django 5.2.6 on 2026-03-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagar", "0049_gastogasolina_parcelamento_gastogeral_parcelamento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gastocontabilidade",
            name="tipo_gasto",
            field=models.CharField(
                choices=[
                    ("SIMPLES", "DAS Simples"),
                    ("FGTS", "FGTS"),
                    ("HONORARIO", "Honorário Contábil"),
                    ("INSS", "INSS"),
                    ("IR", "Imposto de Renda"),
                    ("SeguroFuncionarios", "Seguro dos Funcionarios"),
                    ("Sindicato", "Sindicato"),
                ],
                max_length=20,
                verbose_name="Tipo de Encargo",
            ),
        ),
    ]
