# Generated by Django 5.2.7 on 2026-01-10 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Está na Lixeira?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data da Exclusão"
                    ),
                ),
                (
                    "nome_completo",
                    models.CharField(max_length=255, verbose_name="Nome Completo"),
                ),
                (
                    "cpf",
                    models.CharField(max_length=14, unique=True, verbose_name="CPF"),
                ),
                (
                    "rg",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="RG"
                    ),
                ),
                ("telefone", models.CharField(max_length=20, verbose_name="Telefone")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=255, null=True, verbose_name="E-mail"
                    ),
                ),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["nome_completo"],
            },
        ),
        migrations.CreateModel(
            name="EnderecoCliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("RESIDENCIAL", "Endereço Residencial"),
                            ("OBRA", "Endereço da Obra"),
                        ],
                        default="RESIDENCIAL",
                        max_length=20,
                    ),
                ),
                ("cep", models.CharField(max_length=10)),
                (
                    "endereco",
                    models.CharField(max_length=255, verbose_name="Logradouro"),
                ),
                ("numero", models.CharField(max_length=10, verbose_name="Número")),
                ("bairro", models.CharField(max_length=100)),
                ("cidade", models.CharField(max_length=100)),
                ("uf", models.CharField(max_length=2)),
                (
                    "complemento",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enderecos",
                        to="clientes.cliente",
                    ),
                ),
            ],
        ),
    ]
