# Generated by Django 5.2.6 on 2026-03-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0004_cliente_chave_pix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="telefone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Telefone"
            ),
        ),
    ]
