# Generated by Django 5.2.6 on 2026-03-14 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0005_alter_cliente_telefone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enderecocliente",
            name="bairro",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="enderecocliente",
            name="cep",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="enderecocliente",
            name="cidade",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="enderecocliente",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enderecos",
                to="clientes.cliente",
            ),
        ),
        migrations.AlterField(
            model_name="enderecocliente",
            name="endereco",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Logradouro"
            ),
        ),
        migrations.AlterField(
            model_name="enderecocliente",
            name="numero",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Número"
            ),
        ),
        migrations.AlterField(
            model_name="enderecocliente",
            name="tipo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RESIDENCIAL", "Endereço Residencial"),
                    ("OBRA", "Endereço da Obra"),
                ],
                default="RESIDENCIAL",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="enderecocliente",
            name="uf",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
