# Generated by Django 5.2.6 on 2026-03-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0006_alter_enderecocliente_bairro_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="cnpj",
            field=models.CharField(
                blank=True, max_length=18, null=True, unique=True, verbose_name="CNPJ"
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="inscricao_estadual",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Inscrição Estadual"
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="tipo_pessoa",
            field=models.CharField(
                choices=[("F", "Pessoa Física"), ("J", "Pessoa Jurídica")],
                default="F",
                max_length=1,
                verbose_name="Tipo de Pessoa",
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="nome_completo",
            field=models.CharField(
                max_length=255, verbose_name="Nome Completo / Razão Social"
            ),
        ),
    ]
