# Generated by Django 5.2.7 on 2025-12-26 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("funcionarios", "0006_alter_documentosfuncionario_pis_pasep"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rescisao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_demissao", models.DateField(verbose_name="Data de Demissão")),
                (
                    "motivo",
                    models.CharField(
                        choices=[
                            ("SJC", "Dispensa sem Justa Causa"),
                            ("PJC", "Dispensa por Justa Causa"),
                            ("PED", "Pedido de Demissão"),
                            ("TER", "Término de Contrato"),
                            ("ACO", "Acordo (Art. 484-A)"),
                        ],
                        default="SJC",
                        max_length=3,
                    ),
                ),
                (
                    "tipo_aviso_previo",
                    models.CharField(
                        choices=[
                            ("TRA", "Trabalhado"),
                            ("IND", "Indenizado"),
                            ("NCU", "Não Cumprido (Descontado)"),
                            ("DIS", "Dispensado"),
                        ],
                        default="IND",
                        max_length=3,
                    ),
                ),
                (
                    "saldo_salario",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Saldo de Salário",
                    ),
                ),
                (
                    "aviso_previo_valor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Valor Aviso Prévio",
                    ),
                ),
                (
                    "ferias_vencidas",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Férias Vencidas",
                    ),
                ),
                (
                    "ferias_proporcionais",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Férias Proporcionais",
                    ),
                ),
                (
                    "terco_ferias",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="1/3 de Férias",
                    ),
                ),
                (
                    "decimo_terceiro_proporcional",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="13º Proporcional",
                    ),
                ),
                (
                    "saldo_banco_horas",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Saldo Banco de Horas (R$)",
                    ),
                ),
                (
                    "outros_proventos",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Outros Proventos",
                    ),
                ),
                (
                    "outros_descontos",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Outros Descontos",
                    ),
                ),
                ("observacoes", models.TextField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "funcionario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rescisao",
                        to="funcionarios.funcionario",
                    ),
                ),
            ],
        ),
    ]
