# Generated by Django 5.2.7 on 2025-12-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rescisao", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rescisao",
            old_name="terco_ferias",
            new_name="val_terco_ferias",
        ),
        migrations.RemoveField(
            model_name="rescisao",
            name="aviso_previo_valor",
        ),
        migrations.RemoveField(
            model_name="rescisao",
            name="decimo_terceiro_proporcional",
        ),
        migrations.RemoveField(
            model_name="rescisao",
            name="ferias_proporcionais",
        ),
        migrations.RemoveField(
            model_name="rescisao",
            name="ferias_vencidas",
        ),
        migrations.RemoveField(
            model_name="rescisao",
            name="observacoes",
        ),
        migrations.RemoveField(
            model_name="rescisao",
            name="outros_descontos",
        ),
        migrations.RemoveField(
            model_name="rescisao",
            name="outros_proventos",
        ),
        migrations.RemoveField(
            model_name="rescisao",
            name="saldo_banco_horas",
        ),
        migrations.RemoveField(
            model_name="rescisao",
            name="saldo_salario",
        ),
        migrations.RemoveField(
            model_name="rescisao",
            name="tipo_aviso_previo",
        ),
        migrations.AddField(
            model_name="rescisao",
            name="desc_faltas",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Detalhamento Faltas",
            ),
        ),
        migrations.AddField(
            model_name="rescisao",
            name="outro_nome",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Descrição (Outros)"
            ),
        ),
        migrations.AddField(
            model_name="rescisao",
            name="outro_tipo",
            field=models.CharField(
                choices=[("P", "Provento (+)"), ("D", "Desconto (-)")],
                default="P",
                max_length=1,
                verbose_name="Tipo (Outros)",
            ),
        ),
        migrations.AddField(
            model_name="rescisao",
            name="outro_valor",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Valor (Outros)",
            ),
        ),
        migrations.AddField(
            model_name="rescisao",
            name="val_13_salario",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="13º Salário",
            ),
        ),
        migrations.AddField(
            model_name="rescisao",
            name="val_adiantamento",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Adiantamento",
            ),
        ),
        migrations.AddField(
            model_name="rescisao",
            name="val_atrasos",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Atrasos",
            ),
        ),
        migrations.AddField(
            model_name="rescisao",
            name="val_dias_trabalhados",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Dias Trabalhados",
            ),
        ),
        migrations.AddField(
            model_name="rescisao",
            name="val_faltas",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Faltas",
            ),
        ),
        migrations.AddField(
            model_name="rescisao",
            name="val_ferias",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Férias",
            ),
        ),
        migrations.AddField(
            model_name="rescisao",
            name="val_multa_480",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Desconto Multa Art. 480",
            ),
        ),
        migrations.AddField(
            model_name="rescisao",
            name="val_remunerados",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Remunerados",
            ),
        ),
    ]
