# Generated by Django 5.2.7 on 2026-01-06 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rescisao", "0002_rename_terco_ferias_rescisao_val_terco_ferias_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rescisao",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data da Exclusão"
            ),
        ),
        migrations.AddField(
            model_name="rescisao",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Está na Lixeira?"),
        ),
    ]
