# Generated by Django 5.2.6 on 2026-01-21 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rescisao", "0003_rescisao_deleted_at_rescisao_is_deleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rescisao",
            name="motivo",
        ),
    ]
