# Generated by Django 5.2.6 on 2026-01-28 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rescisao", "0004_remove_rescisao_motivo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rescisao",
            name="outro_nome",
        ),
        migrations.RemoveField(
            model_name="rescisao",
            name="outro_tipo",
        ),
        migrations.RemoveField(
            model_name="rescisao",
            name="outro_valor",
        ),
        migrations.CreateModel(
            name="ItemRescisao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=100, verbose_name="Descrição"),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("P", "Provento (+)"), ("D", "Desconto (-)")],
                        default="P",
                        max_length=1,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "rescisao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens_adicionais",
                        to="rescisao.rescisao",
                    ),
                ),
            ],
        ),
    ]
