# Generated by Django 5.2.6 on 2025-12-07 19:44

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Arquiteta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                (
                    "cpf",
                    models.CharField(blank=True, max_length=14, null=True, unique=True),
                ),
                (
                    "banco",
                    models.CharField(max_length=50, verbose_name="Banco de Pagamento"),
                ),
                ("agencia", models.CharField(max_length=20, verbose_name="Agência")),
                (
                    "conta",
                    models.CharField(max_length=50, verbose_name="Conta Bancária"),
                ),
            ],
            options={
                "verbose_name": "Arquiteta",
                "verbose_name_plural": "Arquitetas",
            },
        ),
        migrations.CreateModel(
            name="ContratoRT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cliente",
                    models.CharField(
                        max_length=255, verbose_name="Nome do Cliente/Projeto"
                    ),
                ),
                ("data_contrato", models.DateField(verbose_name="Data de Assinatura")),
                (
                    "valor_servico",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Valor Total do Serviço",
                    ),
                ),
                (
                    "valor_rt_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Valor Total da RT Devida",
                    ),
                ),
                (
                    "percentual_rt",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Percentual (%)",
                    ),
                ),
                (
                    "saldo_devedor",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=12,
                    ),
                ),
                (
                    "arquiteta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="comissionamento.arquiteta",
                        verbose_name="Arquiteta Responsável",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contrato de RT",
                "verbose_name_plural": "Contratos de RT",
                "ordering": ["-data_contrato"],
            },
        ),
        migrations.CreateModel(
            name="PagamentoRT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_pagamento", models.DateField(verbose_name="Data do Pagamento")),
                (
                    "valor_pago",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor Pago"
                    ),
                ),
                ("observacoes", models.TextField(blank=True, null=True)),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comissionamento.contratort",
                        verbose_name="Contrato de Referência",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pagamento de RT",
                "verbose_name_plural": "Pagamentos de RT",
                "ordering": ["-data_pagamento"],
            },
        ),
    ]
