# Generated by Django 5.2.7 on 2025-12-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comissionamento", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contratort",
            name="percentual_rt",
        ),
        migrations.RemoveField(
            model_name="contratort",
            name="saldo_devedor",
        ),
        migrations.RemoveField(
            model_name="contratort",
            name="valor_rt_total",
        ),
        migrations.AddField(
            model_name="contratort",
            name="data_pagamento",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data do Pagamento"
            ),
        ),
        migrations.AddField(
            model_name="contratort",
            name="observacoes",
            field=models.TextField(blank=True, null=True, verbose_name="Observações"),
        ),
        migrations.AddField(
            model_name="contratort",
            name="valor_pago",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Valor Pago",
            ),
        ),
        migrations.AddField(
            model_name="contratort",
            name="valor_rt",
            field=models.DecimalField(
                decimal_places=2, default=2, max_digits=12, verbose_name="Valor da RT"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contratort",
            name="data_contrato",
            field=models.DateField(verbose_name="Data do Contrato"),
        ),
        migrations.AlterField(
            model_name="contratort",
            name="valor_servico",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Valor do Serviço"
            ),
        ),
        migrations.DeleteModel(
            name="PagamentoRT",
        ),
    ]
