# Generated by Django 5.2.7 on 2025-12-27 22:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comissionamento", "0002_remove_contratort_percentual_rt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contratort",
            name="valor_rt",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Valor da RT",
            ),
        ),
    ]
