# Generated by Django 5.2.7 on 2025-12-28 01:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comissionamento", "0003_alter_contratort_valor_rt"),
    ]

    operations = [
        migrations.AddField(
            model_name="contratort",
            name="percentual",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                verbose_name="Porcentagem (%)",
            ),
        ),
        migrations.AlterField(
            model_name="contratort",
            name="data_contrato",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data do Contrato"
            ),
        ),
        migrations.AlterField(
            model_name="contratort",
            name="valor_rt",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Valor da RT"
            ),
        ),
    ]
