# Generated by Django 5.2.7 on 2026-01-06 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "comissionamento",
            "0004_contratort_percentual_alter_contratort_data_contrato_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="contratort",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data da Exclusão"
            ),
        ),
        migrations.AddField(
            model_name="contratort",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Está na Lixeira?"),
        ),
    ]
