# Generated by Django 5.2.7 on 2026-01-07 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comissionamento", "0005_contratort_deleted_at_contratort_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="arquiteta",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data da Exclusão"
            ),
        ),
        migrations.AddField(
            model_name="arquiteta",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Está na Lixeira?"),
        ),
    ]
