# Generated by Django 5.2.6 on 2026-01-10 19:28

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
        ("comissionamento", "0006_arquiteta_deleted_at_arquiteta_is_deleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contratort",
            name="data_pagamento",
        ),
        migrations.RemoveField(
            model_name="contratort",
            name="valor_pago",
        ),
        migrations.AlterField(
            model_name="contratort",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="clientes.cliente",
                verbose_name="Cliente",
            ),
        ),
        migrations.AlterField(
            model_name="contratort",
            name="percentual",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                verbose_name="Porcentagem RT (%)",
            ),
        ),
        migrations.AlterField(
            model_name="contratort",
            name="valor_rt",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Comissão (Valor da RT)"
            ),
        ),
        migrations.AlterField(
            model_name="contratort",
            name="valor_servico",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                verbose_name="Valor Total do Projeto (Venda)",
            ),
        ),
    ]
