# Generated by Django 5.2.6 on 2026-01-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comissionamento", "0007_remove_contratort_data_pagamento_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contratort",
            name="valor_servico",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Valor Total do Projeto"
            ),
        ),
    ]
