# Generated by Django 5.2.7 on 2025-10-12 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PagamentoFerias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vencimento", models.DateField(verbose_name="Data de Vencimento")),
                (
                    "valor_a_pagar",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "data_pagamento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data do Pagamento"
                    ),
                ),
                ("observacoes", models.TextField(blank=True, null=True)),
                (
                    "data_recibo_contabilidade",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data do Recibo Contábil"
                    ),
                ),
                (
                    "observacoes_recibo_contabilidade",
                    models.TextField(blank=True, null=True),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagamentos_ferias",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PeriodoAquisitivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                ("dias_direito", models.PositiveIntegerField(default=30)),
                ("observacoes", models.TextField(blank=True)),
                (
                    "funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periodos_aquisitivos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ferias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                ("dias_tirados", models.PositiveIntegerField()),
                (
                    "faltas_justificadas_descontadas",
                    models.PositiveIntegerField(default=0),
                ),
                ("observacoes", models.TextField(blank=True)),
                ("ferias_no_recesso_final_ano", models.PositiveIntegerField()),
                ("ferias_no_carnaval", models.PositiveIntegerField()),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "periodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ferias_registradas",
                        to="ferias.periodoaquisitivo",
                    ),
                ),
            ],
        ),
    ]
