# Generated by Django 5.2.6 on 2025-11-02 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ferias", "0001_initial"),
        ("funcionarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagamentoferias",
            name="funcionario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pagamentos_ferias",
                to="funcionarios.funcionario",
            ),
        ),
        migrations.AlterField(
            model_name="periodoaquisitivo",
            name="funcionario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="periodos_aquisitivos",
                to="funcionarios.funcionario",
            ),
        ),
    ]
