# Generated by Django 5.2.6 on 2025-12-08 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ferias", "0002_alter_pagamentoferias_funcionario_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="periodoaquisitivo",
            name="observacoes",
        ),
    ]
