# Generated by Django 5.2.6 on 2025-12-08 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ferias", "0003_remove_periodoaquisitivo_observacoes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ferias",
            name="data_fim",
        ),
        migrations.RemoveField(
            model_name="ferias",
            name="data_inicio",
        ),
    ]
