# Generated by Django 5.2.7 on 2025-12-20 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ferias", "0004_remove_ferias_data_fim_remove_ferias_data_inicio"),
        ("funcionarios", "0004_remove_dadostrabalhistas_saldo_banco_horas"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pagamentoferias",
            name="data_recibo_contabilidade",
        ),
        migrations.RemoveField(
            model_name="pagamentoferias",
            name="observacoes_recibo_contabilidade",
        ),
        migrations.AddField(
            model_name="pagamentoferias",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("pendente", "Pendente"), ("pago", "Pago")],
                default="pendente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ferias",
            name="ferias_no_carnaval",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="ferias",
            name="ferias_no_recesso_final_ano",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name="RecibosContabilidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recibo_de_ferias_contabilidade",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Recibo Contábil"
                    ),
                ),
                ("observacoes", models.TextField(blank=True, null=True)),
                (
                    "funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recibo_contabilidade",
                        to="funcionarios.funcionario",
                    ),
                ),
            ],
        ),
    ]
