# Generated by Django 5.2.7 on 2026-01-06 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ferias", "0005_remove_pagamentoferias_data_recibo_contabilidade_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ferias",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data da Exclusão"
            ),
        ),
        migrations.AddField(
            model_name="ferias",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Está na Lixeira?"),
        ),
        migrations.AddField(
            model_name="pagamentoferias",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data da Exclusão"
            ),
        ),
        migrations.AddField(
            model_name="pagamentoferias",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Está na Lixeira?"),
        ),
    ]
