# Generated by Django 5.2.7 on 2026-01-06 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ferias", "0006_ferias_deleted_at_ferias_is_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="periodoaquisitivo",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data da Exclusão"
            ),
        ),
        migrations.AddField(
            model_name="periodoaquisitivo",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Está na Lixeira?"),
        ),
        migrations.AddField(
            model_name="reciboscontabilidade",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data da Exclusão"
            ),
        ),
        migrations.AddField(
            model_name="reciboscontabilidade",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Está na Lixeira?"),
        ),
    ]
