# Generated by Django 5.2.7 on 2026-01-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ferias", "0007_periodoaquisitivo_deleted_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ferias",
            name="ferias_no_carnaval",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="ferias",
            name="ferias_no_recesso_final_ano",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
