# Generated by Django 5.2.6 on 2026-01-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ferias", "0008_alter_ferias_ferias_no_carnaval_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagamentoferias",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("Pendente", "Pendente"), ("Pago", "Pago")],
                default="pendente",
                max_length=20,
            ),
        ),
    ]
