# Generated by Django 5.2.6 on 2026-01-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ferias", "0009_alter_pagamentoferias_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagamentoferias",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("Pendente", "Pendente"), ("Pago", "Pago")],
                default="Pendente",
                max_length=20,
            ),
        ),
    ]
