# Generated by Django 5.2.6 on 2026-01-21 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ferias", "0010_alter_pagamentoferias_status"),
        ("pagar", "0043_folhapagamento_val_ferias"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagamentoferias",
            name="conta_pagar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pagamento_ferias_origem",
                to="pagar.folhapagamento",
                verbose_name="Conta a Pagar Vinculada",
            ),
        ),
    ]
