# Generated by Django 5.2.6 on 2025-10-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Receber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cliente", models.CharField(max_length=120, verbose_name="Cliente")),
                (
                    "desc",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Descrição"
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor"
                    ),
                ),
                (
                    "when",
                    models.DateField(blank=True, null=True, verbose_name="Recebimento"),
                ),
                (
                    "status",
                    models.CharField(
                        default="Agendado", max_length=30, verbose_name="Status"
                    ),
                ),
            ],
        ),
    ]
