# Generated by Django 5.2.6 on 2025-12-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receber", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receber",
            name="desc",
        ),
        migrations.RemoveField(
            model_name="receber",
            name="status",
        ),
        migrations.RemoveField(
            model_name="receber",
            name="value",
        ),
        migrations.RemoveField(
            model_name="receber",
            name="when",
        ),
        migrations.AddField(
            model_name="receber",
            name="categoria",
            field=models.CharField(max_length=255, null=True, verbose_name="Categoria"),
        ),
        migrations.AddField(
            model_name="receber",
            name="data_pagamento",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data pagamento"
            ),
        ),
        migrations.AddField(
            model_name="receber",
            name="data_vencimento",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data vencimento"
            ),
        ),
        migrations.AddField(
            model_name="receber",
            name="forma_de_recebimento",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Forma de recebimento"
            ),
        ),
        migrations.AddField(
            model_name="receber",
            name="observacoes",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Observações"
            ),
        ),
        migrations.AddField(
            model_name="receber",
            name="valor",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Valor a ser recebido",
            ),
        ),
        migrations.AddField(
            model_name="receber",
            name="valor_estoque",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Valor em estoque",
            ),
        ),
        migrations.AlterField(
            model_name="receber",
            name="cliente",
            field=models.CharField(max_length=255, null=True, verbose_name="Cliente"),
        ),
    ]
