# Generated by Django 5.2.6 on 2025-12-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receber", "0002_remove_receber_desc_remove_receber_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="receber",
            name="status",
            field=models.CharField(
                default="Agendado", max_length=30, verbose_name="Status"
            ),
        ),
    ]
