# Generated by Django 5.2.6 on 2025-12-30 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receber", "0003_receber_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="receber",
            name="tipo_recebimento",
            field=models.CharField(
                choices=[
                    ("VISTA", "À Vista (Caixa/Pix/Débito)"),
                    ("PRAZO", "A Prazo (Boleto/Crédito/Outros)"),
                ],
                default="PRAZO",
                max_length=10,
                verbose_name="Classificação Gerencial",
            ),
        ),
    ]
