# Generated by Django 5.2.6 on 2025-12-30 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receber", "0004_receber_tipo_recebimento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receber",
            name="tipo_recebimento",
            field=models.CharField(
                choices=[("VISTA", "À Vista"), ("PRAZO", "A Prazo")],
                default="PRAZO",
                max_length=10,
                verbose_name="Classificação Gerencial",
            ),
        ),
    ]
