# Generated by Django 5.2.6 on 2025-12-31 01:33

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receber", "0005_alter_receber_tipo_recebimento"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaixaDiario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.DateField(
                        default=django.db.models.functions.datetime.Now,
                        verbose_name="Data",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("E", "Entrada (+)"), ("S", "Saída (-)")],
                        default="S",
                        max_length=1,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        max_length=255, verbose_name="Histórico/Descrição"
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor (R$)"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Lançamento de Caixa",
                "verbose_name_plural": "Caixa Diário",
                "ordering": ["-data", "-created_at"],
            },
        ),
    ]
