# Generated by Django 5.2.7 on 2025-12-31 15:19

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receber", "0006_caixadiario"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome do Banco"),
                ),
                (
                    "agencia",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Agência"
                    ),
                ),
                (
                    "conta",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Conta"
                    ),
                ),
                (
                    "saldo_inicial",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Saldo Inicial da Conta",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MovimentoBanco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.DateField(
                        default=django.db.models.functions.datetime.Now,
                        verbose_name="Data",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("E", "Entrada (+)"), ("S", "Saída (-)")],
                        default="S",
                        max_length=1,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        max_length=255, verbose_name="Histórico/Descrição"
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor (R$)"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "banco",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="receber.banco",
                        verbose_name="Banco/Conta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimento Bancário",
                "verbose_name_plural": "Movimentações Bancárias",
                "ordering": ["-data", "-created_at"],
            },
        ),
    ]
