# Generated by Django 5.2.7 on 2026-01-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receber", "0007_banco_movimentobanco"),
    ]

    operations = [
        migrations.AddField(
            model_name="receber",
            name="descricao",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Descrição"
            ),
        ),
    ]
