# Generated by Django 5.2.7 on 2026-01-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receber", "0008_receber_descricao"),
    ]

    operations = [
        migrations.AddField(
            model_name="receber",
            name="valor_recebido",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Valor Recebido",
            ),
        ),
    ]
