# Generated by Django 5.2.6 on 2026-01-01 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receber", "0009_receber_valor_recebido"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="caixadiario",
            options={},
        ),
        migrations.AlterModelOptions(
            name="movimentobanco",
            options={},
        ),
        migrations.RemoveField(
            model_name="caixadiario",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="caixadiario",
            name="descricao",
        ),
        migrations.RemoveField(
            model_name="caixadiario",
            name="observacoes",
        ),
        migrations.RemoveField(
            model_name="movimentobanco",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="movimentobanco",
            name="descricao",
        ),
        migrations.RemoveField(
            model_name="movimentobanco",
            name="observacoes",
        ),
        migrations.RemoveField(
            model_name="receber",
            name="categoria",
        ),
        migrations.RemoveField(
            model_name="receber",
            name="data_pagamento",
        ),
        migrations.RemoveField(
            model_name="receber",
            name="forma_de_recebimento",
        ),
        migrations.RemoveField(
            model_name="receber",
            name="valor_estoque",
        ),
        migrations.AddField(
            model_name="caixadiario",
            name="historico",
            field=models.CharField(default="-", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="movimentobanco",
            name="historico",
            field=models.CharField(default="-", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="receber",
            name="data_recebimento",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data do Recebimento"
            ),
        ),
        migrations.AddField(
            model_name="receber",
            name="forma_recebimento",
            field=models.CharField(
                choices=[
                    ("DINHEIRO", "Dinheiro"),
                    ("PIX", "Pix"),
                    ("DEBITO", "Cartão de Débito"),
                    ("CREDITO", "Cartão de Crédito"),
                    ("BOLETO", "Boleto"),
                    ("TRANSFERENCIA", "Transferência"),
                    ("OUTROS", "Outros"),
                ],
                default="OUTROS",
                max_length=20,
                verbose_name="Forma de Pagamento",
            ),
        ),
        migrations.AlterField(
            model_name="banco",
            name="agencia",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="banco",
            name="conta",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="banco",
            name="nome",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="banco",
            name="saldo_inicial",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="caixadiario",
            name="data",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="caixadiario",
            name="tipo",
            field=models.CharField(
                choices=[("E", "Entrada"), ("S", "Saída")], max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="caixadiario",
            name="valor",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="movimentobanco",
            name="banco",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movimentos",
                to="receber.banco",
            ),
        ),
        migrations.AlterField(
            model_name="movimentobanco",
            name="data",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="movimentobanco",
            name="tipo",
            field=models.CharField(
                choices=[("E", "Entrada"), ("S", "Saída")], max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="movimentobanco",
            name="valor",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="receber",
            name="cliente",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Cliente"
            ),
        ),
        migrations.AlterField(
            model_name="receber",
            name="data_vencimento",
            field=models.DateField(verbose_name="Data de Vencimento"),
        ),
        migrations.AlterField(
            model_name="receber",
            name="descricao",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Descrição"
            ),
        ),
        migrations.AlterField(
            model_name="receber",
            name="observacoes",
            field=models.TextField(blank=True, null=True, verbose_name="Observações"),
        ),
        migrations.AlterField(
            model_name="receber",
            name="status",
            field=models.CharField(
                choices=[("Pendente", "Pendente"), ("Recebido", "Recebido")],
                default="Pendente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="receber",
            name="tipo_recebimento",
            field=models.CharField(
                choices=[("VISTA", "À Vista"), ("PRAZO", "A Prazo")],
                default="VISTA",
                max_length=10,
                verbose_name="Tipo",
            ),
        ),
        migrations.AlterField(
            model_name="receber",
            name="valor",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Valor Previsto"
            ),
        ),
        migrations.AlterField(
            model_name="receber",
            name="valor_recebido",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Valor Recebido",
            ),
        ),
    ]
