# Generated by Django 5.2.6 on 2026-01-01 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receber", "0010_alter_caixadiario_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="receber",
            name="categoria",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Categoria"
            ),
        ),
    ]
