# Generated by Django 5.2.6 on 2026-01-02 00:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receber", "0011_receber_categoria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receber",
            name="tipo_recebimento",
            field=models.CharField(
                choices=[("VISTA", "À Vista"), ("PRAZO", "A Prazo")],
                default="VISTA",
                max_length=10,
                verbose_name="Tipo de Recebimento",
            ),
        ),
        migrations.AlterField(
            model_name="receber",
            name="valor_recebido",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                null=True,
                verbose_name="Valor Recebido",
            ),
        ),
    ]
