# Generated by Django 5.2.7 on 2026-01-06 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receber", "0012_alter_receber_tipo_recebimento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="receber",
            name="banco_destino",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="receber.banco",
                verbose_name="Conta Bancária (Destino)",
            ),
        ),
        migrations.AddField(
            model_name="receber",
            name="movimento_banco",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recebimento_origem",
                to="receber.movimentobanco",
            ),
        ),
        migrations.AddField(
            model_name="receber",
            name="movimento_caixa",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recebimento_origem",
                to="receber.caixadiario",
            ),
        ),
    ]
