# Generated by Django 5.2.7 on 2026-01-06 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receber", "0013_receber_banco_destino_receber_movimento_banco_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimentobanco",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data da Exclusão"
            ),
        ),
        migrations.AddField(
            model_name="movimentobanco",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Está na Lixeira?"),
        ),
        migrations.AddField(
            model_name="receber",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data da Exclusão"
            ),
        ),
        migrations.AddField(
            model_name="receber",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Está na Lixeira?"),
        ),
    ]
