# Generated by Django 5.2.7 on 2026-01-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "receber",
            "0014_movimentobanco_deleted_at_movimentobanco_is_deleted_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="receber",
            name="parcelamento_uuid",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
