# Generated by Django 5.2.7 on 2026-01-10 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comissionamento", "0006_arquiteta_deleted_at_arquiteta_is_deleted"),
        ("receber", "0015_receber_parcelamento_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="receber",
            name="contrato_rt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parcelas_receber",
                to="comissionamento.contratort",
                verbose_name="Contrato RT Vinculado",
            ),
        ),
    ]
