# Generated by Django 5.2.7 on 2026-01-14 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0002_alter_cliente_cpf"),
        ("receber", "0016_receber_contrato_rt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receber",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="clientes.cliente",
                verbose_name="Cliente",
            ),
        ),
    ]
