# Generated by Django 5.2.6 on 2026-01-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receber", "0017_alter_receber_cliente"),
    ]

    operations = [
        migrations.AddField(
            model_name="caixadiario",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data da Exclusão"
            ),
        ),
        migrations.AddField(
            model_name="caixadiario",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Está na Lixeira?"),
        ),
    ]
